import { defineConfig, sr } from "./apps/cli/src/config-define";

export default defineConfig({
  version: 1,
  defaults: {
    provider: "openai-compatible",
    model: "google/gemma-4-26b-a4b-it",
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,
  },
  modes: {
    keyboard: {
      outDir: "./.rawstep/out/keyboard",
      maxSteps: 20,
      timeoutMs: 180000,
      // verifierAutoComplete: true,
      memory: 5,
      allowedKeys: [
        "ArrowDown",
        "ArrowLeft",
        "ArrowRight",
        "ArrowUp",
        "Enter",
        "Escape",
        "Shift+Tab",
        "Space",
        "Tab",
        "Home",
        "End",
      ],
    },
    "screenreader-strict": {
      outDir: "./.rawstep/out/sr-strict",
      maxSteps: 200,
      timeoutMs: 300000,
      screenshots: "all",
      verifierAutoComplete: true,
      includeRationale: true,
      includeExperienceSummary: true,
      memory: "all",
      screenReaderBackend: "guidepup-voiceover",
      allowedScreenReaderActions: [
        sr.next(),
        sr.previous(),
        sr.heading.next(),
        sr.heading.previous(),
        sr.act(),
        sr.form.next(),
        sr.form.previous(),
      ],
    },
    "screenreader-hybrid": {
      outDir: "./.rawstep/out/sr-hybrid",
      maxSteps: 200,
      timeoutMs: 300000,
      screenshots: "important",
      verifierAutoComplete: true,
      includeRationale: true,
      includeExperienceSummary: true,
      memory: "all",
      screenReaderBackend: "guidepup-virtual",
      allowedScreenReaderActions: [
        sr.next(),
        sr.previous(),
        sr.heading.next(),
        sr.heading.previous(),
        sr.act(),
      ],
    },
  },
});
