// Generated by scripts/build-evidence-catalog.py; do not alter observed speech.
import type { EvidenceCase, EvidenceGroup } from './types.js';
export const EVIDENCE_CATALOG = {
  "sourceCommit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5",
  "normalizationSchemaVersion": "1.0",
  "voiceoverRecordCount": 1290,
  "nvdaRecordCount": 1624,
  "normalizedNvdaSha256": "bd901a3d587cda3536316c75206d573de86ef2382e9f0ba90a8ab83016e36622",
  "normalizedVoiceoverSha256": "2e294d062e623ad60c28e1f709bf2f653fb32a924ad588b2011059606a91f1d0",
  "ariaAtRawResponseSha256": "d4643389f6fc81b16bc20c8be137f7883714bf048bf3228a19613704c44e0405",
  "caseCount": 25,
  "nativeMeasurementByRawstep": false,
  "attribution": "Accessibility Supported: Michael Fairchild and contributors; ARIA-AT: W3C and contributors. See docs/screenreader-evidence.md for distinct licenses."
} as const;
export const EVIDENCE_CASES: readonly EvidenceCase[] = [
  {
    "id": "a11ysupport:tech/aria/aria-pressed:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-15.5-18.5",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": "15.5",
    "pattern": "toggle-button.false",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": false
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, toggle button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:vo_macos:safari:2",
    "at": "voiceover",
    "profileId": "voiceover-safari-15.5-18.5",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": "15.5",
    "pattern": "toggle-button.true",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": true
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, selected, toggle button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/vo_macos/safari/2",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:vo_macos:safari:4",
    "at": "voiceover",
    "profileId": "voiceover-safari-15.5-18.5",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": "15.5",
    "pattern": "toggle-button.mixed",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": "mixed"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, mixed, toggle button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/vo_macos/safari/4",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:vo_macos:safari:6",
    "at": "voiceover",
    "profileId": "voiceover-safari-15.5-18.5",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": "15.5",
    "pattern": "button",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/vo_macos/safari/6",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/input/input-checkbox:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.15-13.0.3",
    "atVersion": "10.15",
    "browser": "safari",
    "browserVersion": "13.0.3",
    "osVersion": "10.15",
    "pattern": "checkbox.unchecked",
    "command": "next_item",
    "elementKind": "checkbox",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "checkbox",
      "name": "Yes",
      "checked": false
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "yes, unchecked, checkbox",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/input/input-checkbox.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "829abcfd69209f861f8b1b43f818626a152362f1252cae107a4a10f3e0ca9e1e",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-12-06",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:apg/checkbox-two-state:vo_macos:safari:20",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.14.5-12.1.1",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "pattern": "checkbox.checked",
    "command": "next_item",
    "elementKind": "checkbox",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "checkbox",
      "name": "Tomato",
      "checked": true
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "Tomato, checked, checkbox",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/apg/checkbox-two-state.json",
      "jsonPointer": "/commands/vo_macos/safari/20",
      "sha256": "488e81f889ff5519152266a015919c423fdf69884ea9a09190b13c5b62756efa",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-05-24",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/buttons:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.14.5-12.1.1",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "pattern": "button",
    "command": "next_item",
    "elementKind": "input-button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "apply"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "apply, button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/buttons.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "cc6b6ebe673609686d02c7eb2c3d08acd22e3b8c33ef57e7314f1fe20c83bcfa",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-08-10",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/links/example1:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.14.5-12.1.1",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "pattern": "link",
    "command": "next_item",
    "elementKind": "link",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "link",
      "name": "sample"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "link, sample",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/links/example1.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "0a07dac9c87332fab975500a8d130f1da41efb973d8ebfc44fe91df63c33734d",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-07-24",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-expanded:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.15.4-13.1",
    "atVersion": "10.15.4",
    "browser": "safari",
    "browserVersion": "13.1",
    "osVersion": "10.15.4",
    "pattern": "disclosure.collapsed",
    "command": "next_focusable_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Show more",
      "expanded": false
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "show more, collapsed, button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-expanded.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "48d710204df6e4df676c46b09fa801d6690e39ef73c9105bb7f3ec3339490f29",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2020-03-30",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-expanded:vo_macos:safari:1",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.15.4-13.1",
    "atVersion": "10.15.4",
    "browser": "safari",
    "browserVersion": "13.1",
    "osVersion": "10.15.4",
    "pattern": "disclosure.expanded",
    "command": "next_focusable_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Show more",
      "expanded": true
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "show more, expanded, button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-expanded.json",
      "jsonPointer": "/commands/vo_macos/safari/1",
      "sha256": "48d710204df6e4df676c46b09fa801d6690e39ef73c9105bb7f3ec3339490f29",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2020-03-30",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-required:vo_macos:safari:0",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.14.5-12.1.1",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "pattern": "textbox.optional",
    "command": "next_focusable_item",
    "elementKind": "input-text",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "textbox",
      "name": "Fruit"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "Fruit, edit text.",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-required.json",
      "jsonPointer": "/commands/vo_macos/safari/0",
      "sha256": "8b8ad942ac8679ba3224b28b65f8a3e363d37c94a057027cab9f816cf0e588bb",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-07-01",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-required:vo_macos:safari:1",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.14.5-12.1.1",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "pattern": "textbox.required",
    "command": "next_focusable_item",
    "elementKind": "input-text",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": true,
      "multiline": false,
      "modal": false,
      "role": "textbox",
      "name": "Veggie"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "Veggie, required, edit text.",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-required.json",
      "jsonPointer": "/commands/vo_macos/safari/1",
      "sha256": "8b8ad942ac8679ba3224b28b65f8a3e363d37c94a057027cab9f816cf0e588bb",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2019-07-01",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/textarea:vo_macos:safari:3",
    "at": "voiceover",
    "profileId": "voiceover-safari-10.15.2-13.0.4",
    "atVersion": "10.15.2",
    "browser": "safari",
    "browserVersion": "13.0.4",
    "osVersion": "10.15.2",
    "pattern": "textarea.valued",
    "command": "next_form_field",
    "elementKind": "textarea",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": true,
      "modal": false,
      "role": "textbox",
      "name": "Tell us about yourself",
      "value": "buffalo buffalo buffalo"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "tell us about yourself, edit text, buffalo buffalo buffalo",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/textarea.json",
      "jsonPointer": "/commands/vo_macos/safari/3",
      "sha256": "5f92b572792cc95fb9931d8166b6173ae2fdf592c4a8b061ebaf3711681d48d1",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2020-01-03",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/buttons:nvda:chrome:0",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.3.1-143",
    "atVersion": "2025.3.1",
    "browser": "chrome",
    "browserVersion": "143",
    "osVersion": "Windows 11 version 21H2",
    "pattern": "button",
    "command": "next_item",
    "elementKind": "input-button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "apply"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "button, apply",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/buttons.json",
      "jsonPointer": "/commands/nvda/chrome/0",
      "sha256": "cc6b6ebe673609686d02c7eb2c3d08acd22e3b8c33ef57e7314f1fe20c83bcfa",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2026-05-03",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/buttons:nvda:chrome:1",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.3.1-143",
    "atVersion": "2025.3.1",
    "browser": "chrome",
    "browserVersion": "143",
    "osVersion": "Windows 11 version 21H2",
    "pattern": "button",
    "command": "next_focusable_item",
    "elementKind": "input-button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "apply"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "apply, button",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/buttons.json",
      "jsonPointer": "/commands/nvda/chrome/1",
      "sha256": "cc6b6ebe673609686d02c7eb2c3d08acd22e3b8c33ef57e7314f1fe20c83bcfa",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2026-05-03",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:0",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.false",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": false
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "toggle button, not pressed, action",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/0",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:1",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.false",
    "command": "next_focusable_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": false
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, toggle button, not pressed",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/1",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:2",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.true",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": true
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "toggle button, pressed, action",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/2",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:3",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.true",
    "command": "next_focusable_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": true
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, toggle button, pressed",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/3",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:4",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.mixed",
    "command": "next_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": "mixed"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "toggle button, not pressed, half checked, action",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/4",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-pressed:nvda:chrome:5",
    "at": "nvda",
    "profileId": "nvda-chrome-2025.1.1-137",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "pattern": "toggle-button.mixed",
    "command": "next_focusable_item",
    "elementKind": "button",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "button",
      "name": "Action",
      "pressed": "mixed"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "action, toggle button, not pressed, half-checked",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-pressed.json",
      "jsonPointer": "/commands/nvda/chrome/5",
      "sha256": "6c33ad1a3d0fca70989520ad4883d67df65a371bf3918a8dad8f27adf739e599",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2025-07-25",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/links/example1:nvda:chrome:0",
    "at": "nvda",
    "profileId": "nvda-chrome-2021.1-92",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "pattern": "link",
    "command": "next_item",
    "elementKind": "link",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "link",
      "name": "sample"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "link, sample",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/links/example1.json",
      "jsonPointer": "/commands/nvda/chrome/0",
      "sha256": "0a07dac9c87332fab975500a8d130f1da41efb973d8ebfc44fe91df63c33734d",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2021-07-30",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/html/links/example1:nvda:chrome:1",
    "at": "nvda",
    "profileId": "nvda-chrome-2021.1-92",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "pattern": "link",
    "command": "next_focusable_item",
    "elementKind": "link",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "link",
      "name": "sample"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "sample, link",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/html/links/example1.json",
      "jsonPointer": "/commands/nvda/chrome/1",
      "sha256": "0a07dac9c87332fab975500a8d130f1da41efb973d8ebfc44fe91df63c33734d",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2021-07-30",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-required:nvda:chrome:0",
    "at": "nvda",
    "profileId": "nvda-chrome-2021.1-92",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "pattern": "textbox.optional",
    "command": "next_focusable_item",
    "elementKind": "input-text",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": false,
      "multiline": false,
      "modal": false,
      "role": "textbox",
      "name": "Fruit"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "Fruit, edit. Blank.",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-required.json",
      "jsonPointer": "/commands/nvda/chrome/0",
      "sha256": "8b8ad942ac8679ba3224b28b65f8a3e363d37c94a057027cab9f816cf0e588bb",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2021-07-28",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  },
  {
    "id": "a11ysupport:tech/aria/aria-required:nvda:chrome:1",
    "at": "nvda",
    "profileId": "nvda-chrome-2021.1-92",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "pattern": "textbox.required",
    "command": "next_focusable_item",
    "elementKind": "input-text",
    "node": {
      "protected": false,
      "disabled": false,
      "readonly": false,
      "required": true,
      "multiline": false,
      "modal": false,
      "role": "textbox",
      "name": "Veggie"
    },
    "context": {
      "readingUnit": "single-control",
      "groupContext": "none",
      "language": "en"
    },
    "reportedSpeech": "Veggie, edit, required. Blank.",
    "semanticInputProvenance": "manual-abstraction-not-native-AX",
    "contextProvenance": "simulation-premise-not-observed-settings",
    "source": {
      "url": "https://github.com/accessibilitysupported/a11ysupport.io/blob/6730ad42e83dd780f63555ab3f14f1c26ea0fae5/data/tests/tech/aria/aria-required.json",
      "jsonPointer": "/commands/nvda/chrome/1",
      "sha256": "8b8ad942ac8679ba3224b28b65f8a3e363d37c94a057027cab9f816cf0e588bb",
      "attribution": "Michael Fairchild and Accessibility Supported contributors",
      "testedOn": "2021-07-28",
      "commit": "6730ad42e83dd780f63555ab3f14f1c26ea0fae5"
    },
    "unknownSettings": [
      "actualOperatingMode",
      "quickNav",
      "verbosity",
      "voice",
      "punctuation",
      "typingEcho",
      "keyboardLayout"
    ]
  }
];
export const EVIDENCE_GROUPS: readonly EvidenceGroup[] = [
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2013.1",
    "browser": "firefox",
    "browserVersion": "111",
    "osVersion": "Windows 11 version 22H2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.2.1",
    "browser": "firefox",
    "browserVersion": "61.0.1",
    "osVersion": "Windows 10 version 1803",
    "records": 32,
    "eligibleReportedSpeechRecords": 13,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 18,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.3.2",
    "browser": "firefox",
    "browserVersion": "62",
    "osVersion": "Windows 10 version 1809",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.3.2",
    "browser": "firefox",
    "browserVersion": "63",
    "osVersion": "Windows 10 version 1809",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.3.2",
    "browser": "firefox",
    "browserVersion": "63.0.1",
    "osVersion": "Windows 10 version 1809",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.3.2",
    "browser": "firefox",
    "browserVersion": "66",
    "osVersion": "Windows 10 version 1809",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2018.4.1",
    "browser": "firefox",
    "browserVersion": "64.0.2",
    "osVersion": "Windows 10 version 1809",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.0.1",
    "browser": "firefox",
    "browserVersion": "66",
    "osVersion": "Windows 10 version 1809",
    "records": 7,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.0.1",
    "browser": "ie",
    "browserVersion": "11",
    "osVersion": "Windows 10 version 1809",
    "records": 7,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.1.1",
    "browser": "firefox",
    "browserVersion": "60",
    "osVersion": "Windows 10 version 1903",
    "records": 5,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.1.1",
    "browser": "firefox",
    "browserVersion": "67",
    "osVersion": "Windows 10 version 1903",
    "records": 29,
    "eligibleReportedSpeechRecords": 27,
    "qualityFlagCounts": {
      "multi-control-reading-unit": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.1.1",
    "browser": "firefox",
    "browserVersion": "68",
    "osVersion": "Windows 10 version 1903",
    "records": 42,
    "eligibleReportedSpeechRecords": 19,
    "qualityFlagCounts": {
      "placeholder-not-literal": 5,
      "literal-status-unreviewed": 12,
      "behavior-prose-not-transcript": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.1.1",
    "browser": "firefox",
    "browserVersion": "79",
    "osVersion": "2004",
    "records": 3,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.1.1",
    "browser": "ie",
    "browserVersion": "11",
    "osVersion": "Windows 10 version 1903",
    "records": 7,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.2",
    "browser": "firefox",
    "browserVersion": "68",
    "osVersion": "Windows 10 version 1903",
    "records": 47,
    "eligibleReportedSpeechRecords": 29,
    "qualityFlagCounts": {
      "multi-control-reading-unit": 14,
      "behavior-prose-not-transcript": 3,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.2",
    "browser": "firefox",
    "browserVersion": "69",
    "osVersion": "Windows 10 version 1903",
    "records": 34,
    "eligibleReportedSpeechRecords": 34,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.2",
    "browser": "firefox",
    "browserVersion": "76",
    "osVersion": "Windows 10 version 1903",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.2.1",
    "browser": "firefox",
    "browserVersion": "69",
    "osVersion": "Windows 10 version 1903",
    "records": 35,
    "eligibleReportedSpeechRecords": 18,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 9,
      "behavior-prose-not-transcript": 8
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.2.1",
    "browser": "firefox",
    "browserVersion": "70",
    "osVersion": "Windows 10 version 1903",
    "records": 26,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "multi-control-reading-unit": 1,
      "behavior-prose-not-transcript": 4,
      "reported-value-may-be-incomplete": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.3.1",
    "browser": "firefox",
    "browserVersion": "116",
    "osVersion": "Windows 10 version 1909",
    "records": 3,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.3.1",
    "browser": "firefox",
    "browserVersion": "73",
    "osVersion": "Windows 10 version 1909",
    "records": 10,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2,
      "literal-status-unreviewed": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.3.1",
    "browser": "firefox",
    "browserVersion": "74",
    "osVersion": "Windows 10 version 1909",
    "records": 6,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2019.3.1",
    "browser": "firefox",
    "browserVersion": "76",
    "osVersion": "Windows 10 version 1909",
    "records": 6,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.1",
    "browser": "firefox",
    "browserVersion": "77",
    "osVersion": "2004",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.1",
    "browser": "firefox",
    "browserVersion": "77",
    "osVersion": "Windows 10 version 2004",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.2",
    "browser": "firefox",
    "browserVersion": "72",
    "osVersion": "Windows 10 version 2004",
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.2",
    "browser": "firefox",
    "browserVersion": "80",
    "osVersion": "2004",
    "records": 43,
    "eligibleReportedSpeechRecords": 31,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 10,
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.2",
    "browser": "firefox",
    "browserVersion": "80",
    "osVersion": "Windows 10 version 2004",
    "records": 15,
    "eligibleReportedSpeechRecords": 13,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.3",
    "browser": "firefox",
    "browserVersion": "100",
    "osVersion": "21H2",
    "records": 8,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.3",
    "browser": "firefox",
    "browserVersion": "82",
    "osVersion": "Windows 10 version 2004",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2020.4",
    "browser": "firefox",
    "browserVersion": "86",
    "osVersion": "Windows 10 version 20h2",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "101",
    "osVersion": "21H2",
    "records": 8,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1,
      "conditional-or-multiple-results": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "91",
    "osVersion": "Windows 10 version 21h1",
    "records": 16,
    "eligibleReportedSpeechRecords": 16,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "chrome",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "records": 292,
    "eligibleReportedSpeechRecords": 188,
    "qualityFlagCounts": {
      "placeholder-not-literal": 5,
      "literal-status-unreviewed": 32,
      "behavior-prose-not-transcript": 53,
      "state-output-contradiction": 2,
      "conditional-or-multiple-results": 2,
      "multi-control-reading-unit": 8,
      "no-output-description-not-spoken-text": 1,
      "reported-value-may-be-incomplete": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "edge",
    "browserVersion": "101",
    "osVersion": "21H2",
    "records": 8,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1,
      "conditional-or-multiple-results": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "edge",
    "browserVersion": "91",
    "osVersion": "Windows 10 version 21h1",
    "records": 16,
    "eligibleReportedSpeechRecords": 16,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "edge",
    "browserVersion": "92",
    "osVersion": "Windows 10 version 21h1",
    "records": 308,
    "eligibleReportedSpeechRecords": 200,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 34,
      "placeholder-not-literal": 5,
      "behavior-prose-not-transcript": 55,
      "state-output-contradiction": 2,
      "conditional-or-multiple-results": 2,
      "multi-control-reading-unit": 8,
      "no-output-description-not-spoken-text": 1,
      "reported-value-may-be-incomplete": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.1",
    "browser": "firefox",
    "browserVersion": "90",
    "osVersion": "Windows 10 version 21h1",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "chrome",
    "browserVersion": "94",
    "osVersion": "Windows 10 version 21h1",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "chrome",
    "browserVersion": "96",
    "osVersion": "Windows 10 version 21h1",
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "edge",
    "browserVersion": "94",
    "osVersion": "Windows 10 version 21h1",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "edge",
    "browserVersion": "96",
    "osVersion": "Windows 10 version 21h1",
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "firefox",
    "browserVersion": "93",
    "osVersion": "Windows 10 version 1909",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.2",
    "browser": "firefox",
    "browserVersion": "94",
    "osVersion": "Windows 10 version 21h1",
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3",
    "browser": "chrome",
    "browserVersion": "96",
    "osVersion": "Windows 10 version 21h1",
    "records": 24,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3",
    "browser": "edge",
    "browserVersion": "96",
    "osVersion": "Windows 10 version 21h1",
    "records": 24,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3",
    "browser": "firefox",
    "browserVersion": "95",
    "osVersion": "Windows 10 version 21h1",
    "records": 24,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.1",
    "browser": "chrome",
    "browserVersion": "97",
    "osVersion": "Windows 10 version 21h1",
    "records": 36,
    "eligibleReportedSpeechRecords": 30,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.1",
    "browser": "edge",
    "browserVersion": "97",
    "osVersion": "Windows 10 version 21h1",
    "records": 36,
    "eligibleReportedSpeechRecords": 30,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.1",
    "browser": "firefox",
    "browserVersion": "96",
    "osVersion": "Windows 10 version 21h1",
    "records": 36,
    "eligibleReportedSpeechRecords": 30,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.3",
    "browser": "chrome",
    "browserVersion": "101",
    "osVersion": "Windows 10 version 21h1",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.3",
    "browser": "edge",
    "browserVersion": "101",
    "osVersion": "Windows 10 version 21h1",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2021.3.3",
    "browser": "firefox",
    "browserVersion": "99",
    "osVersion": "Windows 10 version 21h1",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.2.2",
    "browser": "chrome",
    "browserVersion": "105",
    "osVersion": "Windows 11 version 21H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.2.2",
    "browser": "edge",
    "browserVersion": "105",
    "osVersion": "Windows 11 version 21H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.2.2",
    "browser": "firefox",
    "browserVersion": "104",
    "osVersion": "Windows 11 version 21H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.1",
    "browser": "chrome",
    "browserVersion": "107",
    "osVersion": "Windows 11 version 22h2",
    "records": 12,
    "eligibleReportedSpeechRecords": 9,
    "qualityFlagCounts": {
      "no-output-description-not-spoken-text": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.1",
    "browser": "edge",
    "browserVersion": "107",
    "osVersion": "Windows 11 version 22h2",
    "records": 12,
    "eligibleReportedSpeechRecords": 9,
    "qualityFlagCounts": {
      "no-output-description-not-spoken-text": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.1",
    "browser": "firefox",
    "browserVersion": "106",
    "osVersion": "Windows 11 version 22h2",
    "records": 12,
    "eligibleReportedSpeechRecords": 9,
    "qualityFlagCounts": {
      "no-output-description-not-spoken-text": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.2",
    "browser": "chrome",
    "browserVersion": "107",
    "osVersion": "Windows 11 version 22H2",
    "records": 12,
    "eligibleReportedSpeechRecords": 10,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.2",
    "browser": "edge",
    "browserVersion": "107",
    "osVersion": "Windows 11 version 22H2",
    "records": 12,
    "eligibleReportedSpeechRecords": 10,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.3.2",
    "browser": "firefox",
    "browserVersion": "107",
    "osVersion": "Windows 11 version 22H2",
    "records": 11,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 2,
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.4",
    "browser": "chrome",
    "browserVersion": "109",
    "osVersion": "Windows 11 version 22h2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.4",
    "browser": "edge",
    "browserVersion": "108",
    "osVersion": "Windows 11 version 22h2",
    "records": 5,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.4",
    "browser": "edge",
    "browserVersion": "109",
    "osVersion": "Windows 11 version 22h2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.4",
    "browser": "firefox",
    "browserVersion": "108",
    "osVersion": "Windows 11 version 22h2",
    "records": 5,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2022.4",
    "browser": "firefox",
    "browserVersion": "109",
    "osVersion": "Windows 11 version 22h2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "111",
    "osVersion": "Windows 11 version 22H2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "114",
    "osVersion": "Windows 11 version 22H2",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "115",
    "osVersion": "Windows 11 version 22H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "116",
    "osVersion": "Windows 11 version 22H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "116",
    "osVersion": "Windows 11 version 22h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "chrome",
    "browserVersion": "129",
    "osVersion": "Windows 11 version 22H2",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "edge",
    "browserVersion": "111",
    "osVersion": "Windows 11 version 22H2",
    "records": 1,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "edge",
    "browserVersion": "114",
    "osVersion": "Windows 11 version 22H2",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "edge",
    "browserVersion": "114",
    "osVersion": "Windows 11 version 22h2",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "edge",
    "browserVersion": "115",
    "osVersion": "Windows 11 version 22H2",
    "records": 6,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "edge",
    "browserVersion": "129",
    "osVersion": "Windows 11 version 22H2",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "firefox",
    "browserVersion": "115",
    "osVersion": "Windows 11 version 22H2",
    "records": 5,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {
      "placeholder-not-literal": 1,
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "firefox",
    "browserVersion": "116",
    "osVersion": "Windows 11 version 22h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.1",
    "browser": "firefox",
    "browserVersion": "131",
    "osVersion": "Windows 11 version 22H2",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.2",
    "browser": "chrome",
    "browserVersion": "116",
    "osVersion": "Windows 11 version 22h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.2",
    "browser": "edge",
    "browserVersion": "115",
    "osVersion": "Windows 11 version 22h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.2",
    "browser": "firefox",
    "browserVersion": "116",
    "osVersion": "Windows 11 version 22h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.3.3",
    "browser": "chrome",
    "browserVersion": "121",
    "osVersion": "Windows 11 version 22H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.3.3",
    "browser": "edge",
    "browserVersion": "121",
    "osVersion": "Windows 11 version 22H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2023.3.3",
    "browser": "firefox",
    "browserVersion": "122",
    "osVersion": "Windows 11 version 22H2",
    "records": 3,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.3",
    "browser": "chrome",
    "browserVersion": "129",
    "osVersion": "Windows 11 version 23h2",
    "records": 5,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.3",
    "browser": "edge",
    "browserVersion": "130.0.2849.27",
    "osVersion": "Windows 11 version 23h2",
    "records": 7,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.4",
    "browser": "chrome",
    "browserVersion": "129",
    "osVersion": "Windows 11 version 23h2",
    "records": 35,
    "eligibleReportedSpeechRecords": 33,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.4",
    "browser": "edge",
    "browserVersion": "130",
    "osVersion": "Windows 11 version 23h2",
    "records": 21,
    "eligibleReportedSpeechRecords": 21,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.4.2",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 11 version 24h2",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2024.4.2",
    "browser": "firefox",
    "browserVersion": "138.0.4",
    "osVersion": "Windows 11 version 24h2",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2025.1",
    "browser": "edge",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "records": 7,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2025.1.1",
    "browser": "chrome",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "records": 29,
    "eligibleReportedSpeechRecords": 21,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 2,
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 2,
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2025.1.1",
    "browser": "edge",
    "browserVersion": "137",
    "osVersion": "Windows 10 Pro version 2009",
    "records": 22,
    "eligibleReportedSpeechRecords": 17,
    "qualityFlagCounts": {
      "conditional-or-multiple-results": 2,
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2025.1.1",
    "browser": "firefox",
    "browserVersion": "139",
    "osVersion": "Windows 10 Pro version 2009",
    "records": 29,
    "eligibleReportedSpeechRecords": 18,
    "qualityFlagCounts": {
      "no-output-description-not-spoken-text": 1,
      "behavior-prose-not-transcript": 4,
      "conditional-or-multiple-results": 1,
      "placeholder-not-literal": 2,
      "literal-status-unreviewed": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "nvda",
    "atVersion": "2025.3.1",
    "browser": "chrome",
    "browserVersion": "143",
    "osVersion": "Windows 11 version 21H2",
    "records": 9,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14",
    "browser": "safari",
    "browserVersion": "12",
    "osVersion": "10.14",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.1",
    "browser": "safari",
    "browserVersion": "12.0.1",
    "osVersion": "10.14.1",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.2",
    "browser": "safari",
    "browserVersion": "12.0.2",
    "osVersion": "10.14.2",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.4",
    "browser": "safari",
    "browserVersion": "12.1",
    "osVersion": "10.14.4",
    "records": 7,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.5",
    "browser": "chrome",
    "browserVersion": "75",
    "osVersion": "10.13.5",
    "records": 4,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.13.5",
    "records": 8,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.5",
    "browser": "safari",
    "browserVersion": "12.1.1",
    "osVersion": "10.14.5",
    "records": 69,
    "eligibleReportedSpeechRecords": 49,
    "qualityFlagCounts": {
      "placeholder-not-literal": 3,
      "literal-status-unreviewed": 11,
      "behavior-prose-not-transcript": 6
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.6",
    "browser": "safari",
    "browserVersion": "12.1.2",
    "osVersion": "10.14.5",
    "records": 48,
    "eligibleReportedSpeechRecords": 39,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 6,
      "abridged-output": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.6",
    "browser": "safari",
    "browserVersion": "12.1.2",
    "osVersion": "10.14.6",
    "records": 28,
    "eligibleReportedSpeechRecords": 28,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.14.6",
    "browser": "safari",
    "browserVersion": "13.0.1",
    "osVersion": "10.14.6",
    "records": 6,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15",
    "browser": "safari",
    "browserVersion": "13.0.2",
    "osVersion": "10.15",
    "records": 39,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 7,
      "behavior-prose-not-transcript": 12
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15",
    "browser": "safari",
    "browserVersion": "13.0.3",
    "osVersion": "10.15",
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.2",
    "browser": "safari",
    "browserVersion": "13.0.4",
    "osVersion": "10.15.2",
    "records": 33,
    "eligibleReportedSpeechRecords": 15,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 18
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.3",
    "browser": "safari",
    "browserVersion": "13.0.5",
    "osVersion": "10.15.3",
    "records": 9,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "literal-status-unreviewed": 2,
      "no-output-description-not-spoken-text": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.4",
    "browser": "safari",
    "browserVersion": "13.1",
    "osVersion": "10.15.4",
    "records": 14,
    "eligibleReportedSpeechRecords": 13,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.5",
    "browser": "safari",
    "browserVersion": "13.1.1",
    "osVersion": "10.15.5",
    "records": 9,
    "eligibleReportedSpeechRecords": 9,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.6",
    "browser": "safari",
    "browserVersion": "13.1.2",
    "osVersion": "10.15.6",
    "records": 17,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2,
      "behavior-prose-not-transcript": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.6",
    "browser": "safari",
    "browserVersion": "14.0",
    "osVersion": "10.15.6",
    "records": 53,
    "eligibleReportedSpeechRecords": 43,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 10
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "10.15.7",
    "browser": "safari",
    "browserVersion": "14.0",
    "osVersion": "10.15.7",
    "records": 3,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.2.2",
    "browser": "safari",
    "browserVersion": "14.0.3",
    "osVersion": "11.2.2",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6",
    "browser": "safari",
    "browserVersion": "15.0",
    "osVersion": "11.6",
    "records": 4,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1,
      "placeholder-not-literal": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6.1",
    "browser": "safari",
    "browserVersion": "11.6.1",
    "osVersion": "11.6.1",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6.1",
    "browser": "safari",
    "browserVersion": "15.1",
    "osVersion": "11.6.1",
    "records": 28,
    "eligibleReportedSpeechRecords": 24,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6.2",
    "browser": "safari",
    "browserVersion": "15.1",
    "osVersion": "11.6.2",
    "records": 10,
    "eligibleReportedSpeechRecords": 8,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6.2",
    "browser": "safari",
    "browserVersion": "15.3",
    "osVersion": "11.6.2",
    "records": 10,
    "eligibleReportedSpeechRecords": 8,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "11.6.3",
    "browser": "safari",
    "browserVersion": "15.3",
    "osVersion": "11.6.3",
    "records": 10,
    "eligibleReportedSpeechRecords": 8,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "12.2.1",
    "browser": "safari",
    "browserVersion": "15.3",
    "osVersion": "12.2.1",
    "records": 10,
    "eligibleReportedSpeechRecords": 7,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2,
      "conditional-or-multiple-results": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "12.6",
    "browser": "safari",
    "browserVersion": "16.0",
    "osVersion": "12.6",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.0",
    "browser": "safari",
    "browserVersion": "16.1",
    "osVersion": "13.0",
    "records": 12,
    "eligibleReportedSpeechRecords": 10,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "no-output-description-not-spoken-text": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.0.1",
    "browser": "safari",
    "browserVersion": "16.1",
    "osVersion": "13.0.1",
    "records": 13,
    "eligibleReportedSpeechRecords": 6,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1,
      "literal-status-unreviewed": 4,
      "conditional-or-multiple-results": 1,
      "no-output-description-not-spoken-text": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.1",
    "browser": "safari",
    "browserVersion": "16.2",
    "osVersion": "13.1",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.1",
    "browser": "safari",
    "browserVersion": "6.1",
    "osVersion": "13.1",
    "records": 5,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.2.1",
    "browser": "safari",
    "browserVersion": "16.3",
    "osVersion": "13.2.1",
    "records": 1,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.4.1",
    "browser": "safari",
    "browserVersion": "16.5.1",
    "osVersion": "13.4.1",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "13.5",
    "browser": "safari",
    "browserVersion": "16.6",
    "osVersion": "13.5",
    "records": 20,
    "eligibleReportedSpeechRecords": 13,
    "qualityFlagCounts": {
      "literal-status-unreviewed": 3,
      "no-output-description-not-spoken-text": 4
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "14.3",
    "browser": "safari",
    "browserVersion": "17.3",
    "osVersion": "14.3",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "placeholder-not-literal": 1,
      "literal-status-unreviewed": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "14.4",
    "browser": "safari",
    "browserVersion": "17.4",
    "osVersion": "14.4",
    "records": 2,
    "eligibleReportedSpeechRecords": 0,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15",
    "browser": "safari",
    "browserVersion": "18.0",
    "osVersion": "15",
    "records": 2,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15.4.1",
    "browser": "safari",
    "browserVersion": "18.4",
    "osVersion": "15.4.1",
    "records": 2,
    "eligibleReportedSpeechRecords": 1,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": "15.5",
    "records": 24,
    "eligibleReportedSpeechRecords": 17,
    "qualityFlagCounts": {
      "no-output-description-not-spoken-text": 2,
      "literal-status-unreviewed": 2,
      "placeholder-not-literal": 3
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15.5",
    "browser": "safari",
    "browserVersion": "26.0",
    "osVersion": "15.5",
    "records": 7,
    "eligibleReportedSpeechRecords": 3,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 2,
      "literal-status-unreviewed": 2
    }
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15.7.3",
    "browser": "safari",
    "browserVersion": "18.6",
    "osVersion": "15.7.3",
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {}
  },
  {
    "source": "a11ysupport",
    "at": "voiceover",
    "atVersion": "15.7.3",
    "browser": "safari",
    "browserVersion": "26.2",
    "osVersion": "15.7.3",
    "records": 3,
    "eligibleReportedSpeechRecords": 2,
    "qualityFlagCounts": {
      "behavior-prose-not-transcript": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "26",
    "browser": "safari",
    "browserVersion": "26",
    "osVersion": null,
    "records": 20,
    "eligibleReportedSpeechRecords": 20,
    "qualityFlagCounts": {
      "not_vendor_approved": 20,
      "completion_precedes_current_record_start_possibly_carried_forward": 14
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.6.1",
    "browser": "safari",
    "browserVersion": "18.6",
    "osVersion": null,
    "records": 120,
    "eligibleReportedSpeechRecords": 100,
    "qualityFlagCounts": {
      "not_vendor_approved": 110,
      "completion_precedes_current_record_start_possibly_carried_forward": 26,
      "reported_untestable": 13,
      "reported_negative_side_effect": 15,
      "no_output_sentinel_not_speech": 7
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.6.1",
    "browser": "safari",
    "browserVersion": "26.2",
    "osVersion": null,
    "records": 16,
    "eligibleReportedSpeechRecords": 16,
    "qualityFlagCounts": {
      "not_vendor_approved": 16,
      "reported_negative_side_effect": 2
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "26",
    "browser": "safari",
    "browserVersion": "26.2",
    "osVersion": null,
    "records": 21,
    "eligibleReportedSpeechRecords": 15,
    "qualityFlagCounts": {
      "reported_negative_side_effect": 6,
      "not_vendor_approved": 21,
      "reported_untestable": 4,
      "no_output_sentinel_not_speech": 2
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.6",
    "browser": "safari",
    "browserVersion": "18.6",
    "osVersion": null,
    "records": 136,
    "eligibleReportedSpeechRecords": 113,
    "qualityFlagCounts": {
      "not_vendor_approved": 136,
      "completion_precedes_current_record_start_possibly_carried_forward": 91,
      "reported_untestable": 19,
      "reported_negative_side_effect": 23,
      "no_output_sentinel_not_speech": 4
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.2",
    "browser": "safari",
    "browserVersion": "17.2.0",
    "osVersion": null,
    "records": 11,
    "eligibleReportedSpeechRecords": 11,
    "qualityFlagCounts": {
      "completion_precedes_current_record_start_possibly_carried_forward": 11,
      "not_vendor_approved": 3
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.4",
    "browser": "safari",
    "browserVersion": "17.4.1",
    "osVersion": null,
    "records": 10,
    "eligibleReportedSpeechRecords": 9,
    "qualityFlagCounts": {
      "not_vendor_approved": 10,
      "completion_precedes_current_record_start_possibly_carried_forward": 6,
      "reported_untestable": 1,
      "reported_negative_side_effect": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "13.7.2",
    "browser": "safari",
    "browserVersion": "18.3",
    "osVersion": null,
    "records": 6,
    "eligibleReportedSpeechRecords": 5,
    "qualityFlagCounts": {
      "not_vendor_approved": 6,
      "completion_precedes_current_record_start_possibly_carried_forward": 6,
      "no_output_sentinel_not_speech": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "13.7.2",
    "browser": "safari",
    "browserVersion": "14.1.2",
    "osVersion": null,
    "records": 37,
    "eligibleReportedSpeechRecords": 33,
    "qualityFlagCounts": {
      "not_vendor_approved": 37,
      "completion_precedes_current_record_start_possibly_carried_forward": 37,
      "reported_negative_side_effect": 5,
      "no_output_sentinel_not_speech": 4
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.7",
    "browser": "safari",
    "browserVersion": "18.0.1",
    "osVersion": null,
    "records": 43,
    "eligibleReportedSpeechRecords": 42,
    "qualityFlagCounts": {
      "not_vendor_approved": 43,
      "completion_precedes_current_record_start_possibly_carried_forward": 43,
      "reported_negative_side_effect": 5,
      "no_output_sentinel_not_speech": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.3.1 ",
    "browser": "safari",
    "browserVersion": "18",
    "osVersion": null,
    "records": 56,
    "eligibleReportedSpeechRecords": 54,
    "qualityFlagCounts": {
      "not_vendor_approved": 56,
      "completion_precedes_current_record_start_possibly_carried_forward": 30,
      "reported_untestable": 2,
      "reported_negative_side_effect": 7
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.6.1",
    "browser": "safari",
    "browserVersion": "17",
    "osVersion": null,
    "records": 25,
    "eligibleReportedSpeechRecords": 23,
    "qualityFlagCounts": {
      "not_vendor_approved": 25,
      "completion_precedes_current_record_start_possibly_carried_forward": 25,
      "reported_negative_side_effect": 1,
      "no_output_sentinel_not_speech": 1,
      "possible_test_harness_capture": 1,
      "unusually_long_capture_review_required": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.6.1",
    "browser": "safari",
    "browserVersion": "26",
    "osVersion": null,
    "records": 25,
    "eligibleReportedSpeechRecords": 24,
    "qualityFlagCounts": {
      "not_vendor_approved": 25,
      "completion_precedes_current_record_start_possibly_carried_forward": 21,
      "reported_untestable": 1,
      "reported_negative_side_effect": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.3.1 ",
    "browser": "safari",
    "browserVersion": "18.3",
    "osVersion": null,
    "records": 36,
    "eligibleReportedSpeechRecords": 36,
    "qualityFlagCounts": {
      "not_vendor_approved": 36,
      "completion_precedes_current_record_start_possibly_carried_forward": 36,
      "reported_negative_side_effect": 4
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.4.1",
    "browser": "safari",
    "browserVersion": "18.5",
    "osVersion": null,
    "records": 12,
    "eligibleReportedSpeechRecords": 12,
    "qualityFlagCounts": {
      "not_vendor_approved": 12,
      "completion_precedes_current_record_start_possibly_carried_forward": 12
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.4.1",
    "browser": "safari",
    "browserVersion": "18.4",
    "osVersion": null,
    "records": 36,
    "eligibleReportedSpeechRecords": 36,
    "qualityFlagCounts": {
      "not_vendor_approved": 36,
      "reported_negative_side_effect": 2
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "13.7",
    "browser": "safari",
    "browserVersion": "17",
    "osVersion": null,
    "records": 23,
    "eligibleReportedSpeechRecords": 23,
    "qualityFlagCounts": {
      "not_vendor_approved": 23,
      "completion_precedes_current_record_start_possibly_carried_forward": 23,
      "reported_negative_side_effect": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "13.7",
    "browser": "safari",
    "browserVersion": "18.0.1",
    "osVersion": null,
    "records": 25,
    "eligibleReportedSpeechRecords": 25,
    "qualityFlagCounts": {
      "not_vendor_approved": 25,
      "completion_precedes_current_record_start_possibly_carried_forward": 25,
      "reported_negative_side_effect": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "15.2",
    "browser": "safari",
    "browserVersion": "18",
    "osVersion": null,
    "records": 16,
    "eligibleReportedSpeechRecords": 16,
    "qualityFlagCounts": {}
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.5",
    "browser": "safari",
    "browserVersion": "17.5",
    "osVersion": null,
    "records": 4,
    "eligibleReportedSpeechRecords": 4,
    "qualityFlagCounts": {
      "not_vendor_approved": 4,
      "completion_precedes_current_record_start_possibly_carried_forward": 4,
      "reported_negative_side_effect": 1
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.5",
    "browser": "safari",
    "browserVersion": "17",
    "osVersion": null,
    "records": 16,
    "eligibleReportedSpeechRecords": 16,
    "qualityFlagCounts": {
      "not_vendor_approved": 16,
      "completion_precedes_current_record_start_possibly_carried_forward": 16,
      "reported_negative_side_effect": 6
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.4",
    "browser": "safari",
    "browserVersion": "17.4.0",
    "osVersion": null,
    "records": 26,
    "eligibleReportedSpeechRecords": 21,
    "qualityFlagCounts": {
      "not_vendor_approved": 26,
      "completion_precedes_current_record_start_possibly_carried_forward": 26,
      "reported_negative_side_effect": 2,
      "no_output_sentinel_not_speech": 5
    }
  },
  {
    "source": "aria-at",
    "at": "voiceover",
    "atVersion": "14.4.1",
    "browser": "safari",
    "browserVersion": "17",
    "osVersion": null,
    "records": 22,
    "eligibleReportedSpeechRecords": 22,
    "qualityFlagCounts": {
      "not_vendor_approved": 22,
      "completion_precedes_current_record_start_possibly_carried_forward": 18,
      "reported_negative_side_effect": 2
    }
  }
];
