// This file is generated by packages/action-catalog/scripts/generate.ts.
// Do not edit by hand.

export const SCREEN_READER_BACKEND_IDS = [
  "guidepup-voiceover",
  "guidepup-nvda",
  "guidepup-virtual"
] as const;

export const KEYBOARD_ACTION_DEFINITIONS = {
  "Tab": {
    "helperPath": "tab",
    "cliToken": "Tab",
    "defaultAllowed": true
  },
  "Shift+Tab": {
    "helperPath": "shiftTab",
    "cliToken": "Shift+Tab",
    "defaultAllowed": true
  },
  "Home": {
    "helperPath": "home",
    "cliToken": "Home",
    "defaultAllowed": true
  },
  "End": {
    "helperPath": "end",
    "cliToken": "End",
    "defaultAllowed": true
  },
  "ArrowUp": {
    "helperPath": "arrow.up",
    "cliToken": "ArrowUp",
    "defaultAllowed": true
  },
  "ArrowDown": {
    "helperPath": "arrow.down",
    "cliToken": "ArrowDown",
    "defaultAllowed": true
  },
  "ArrowLeft": {
    "helperPath": "arrow.left",
    "cliToken": "ArrowLeft",
    "defaultAllowed": true
  },
  "ArrowRight": {
    "helperPath": "arrow.right",
    "cliToken": "ArrowRight",
    "defaultAllowed": true
  },
  "Backspace": {
    "helperPath": "backspace",
    "cliToken": "Backspace",
    "defaultAllowed": false
  },
  "Delete": {
    "helperPath": "delete",
    "cliToken": "Delete",
    "defaultAllowed": false
  },
  "Enter": {
    "helperPath": "enter",
    "cliToken": "Enter",
    "defaultAllowed": true
  },
  "Shift+Enter": {
    "helperPath": "shiftEnter",
    "cliToken": "Shift+Enter",
    "defaultAllowed": false
  },
  "Space": {
    "helperPath": "space",
    "cliToken": "Space",
    "defaultAllowed": true
  },
  "Escape": {
    "helperPath": "escape",
    "cliToken": "Escape",
    "defaultAllowed": true
  },
  "Mod+A": {
    "helperPath": "mod.a",
    "cliToken": "Mod+A",
    "defaultAllowed": false
  },
  "Mod+Backspace": {
    "helperPath": "mod.backspace",
    "cliToken": "Mod+Backspace",
    "defaultAllowed": false
  },
  "Mod+Delete": {
    "helperPath": "mod.delete",
    "cliToken": "Mod+Delete",
    "defaultAllowed": false
  },
  "Mod+Z": {
    "helperPath": "mod.z",
    "cliToken": "Mod+Z",
    "defaultAllowed": false
  },
  "Mod+Shift+Z": {
    "helperPath": "mod.shiftZ",
    "cliToken": "Mod+Shift+Z",
    "defaultAllowed": false
  }
} as const;
export const KEYBOARD_HELPER_PATH_TO_KEY = {
  "tab": "Tab",
  "shiftTab": "Shift+Tab",
  "home": "Home",
  "end": "End",
  "arrow.up": "ArrowUp",
  "arrow.down": "ArrowDown",
  "arrow.left": "ArrowLeft",
  "arrow.right": "ArrowRight",
  "backspace": "Backspace",
  "delete": "Delete",
  "enter": "Enter",
  "shiftEnter": "Shift+Enter",
  "space": "Space",
  "escape": "Escape",
  "mod.a": "Mod+A",
  "mod.backspace": "Mod+Backspace",
  "mod.delete": "Mod+Delete",
  "mod.z": "Mod+Z",
  "mod.shiftZ": "Mod+Shift+Z"
} as const;
export const SUPPORTED_KEYS = [
  "Tab",
  "Shift+Tab",
  "Home",
  "End",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Backspace",
  "Delete",
  "Enter",
  "Shift+Enter",
  "Space",
  "Escape",
  "Mod+A",
  "Mod+Backspace",
  "Mod+Delete",
  "Mod+Z",
  "Mod+Shift+Z"
] as const;
export const DEFAULT_ALLOWED_KEYS = [
  "Tab",
  "Shift+Tab",
  "Home",
  "End",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Enter",
  "Space",
  "Escape"
] as const;
export const SUPPORTED_KEY_LABELS = "Tab, Shift+Tab, Home, End, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Backspace, Delete, Enter, Shift+Enter, Space, Escape, Mod+A, Mod+Backspace, Mod+Delete, Mod+Z, Mod+Shift+Z" as const;

export const SCREEN_READER_ACTION_DEFINITIONS = {
  "next": {
    "helperPath": "next",
    "promptToken": "sr.next",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "previous": {
    "helperPath": "previous",
    "promptToken": "sr.previous",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "act": {
    "helperPath": "act",
    "promptToken": "sr.act",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "interact": {
    "helperPath": "interact",
    "promptToken": "sr.interact",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "stopInteracting": {
    "helperPath": "stopInteracting",
    "promptToken": "sr.stopInteracting",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "press": {
    "helperPath": "press",
    "promptToken": "sr.press",
    "kind": "invoke",
    "argumentKind": "key",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": false
  },
  "type": {
    "helperPath": "type",
    "promptToken": "sr.type",
    "kind": "invoke",
    "argumentKind": "text",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "click": {
    "helperPath": "click",
    "promptToken": "sr.click",
    "kind": "invoke",
    "argumentKind": "click",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.tab": {
    "helperPath": "key.tab",
    "promptToken": "sr.key.tab",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Tab",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.shiftTab": {
    "helperPath": "key.shiftTab",
    "promptToken": "sr.key.shiftTab",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Shift+Tab",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.home": {
    "helperPath": "key.home",
    "promptToken": "sr.key.home",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Home",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.end": {
    "helperPath": "key.end",
    "promptToken": "sr.key.end",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "End",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.arrow.up": {
    "helperPath": "key.arrow.up",
    "promptToken": "sr.key.arrow.up",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "ArrowUp",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.arrow.down": {
    "helperPath": "key.arrow.down",
    "promptToken": "sr.key.arrow.down",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "ArrowDown",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.arrow.left": {
    "helperPath": "key.arrow.left",
    "promptToken": "sr.key.arrow.left",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "ArrowLeft",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.arrow.right": {
    "helperPath": "key.arrow.right",
    "promptToken": "sr.key.arrow.right",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "ArrowRight",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.backspace": {
    "helperPath": "key.backspace",
    "promptToken": "sr.key.backspace",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Backspace",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.delete": {
    "helperPath": "key.delete",
    "promptToken": "sr.key.delete",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Delete",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.enter": {
    "helperPath": "key.enter",
    "promptToken": "sr.key.enter",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Enter",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.shiftEnter": {
    "helperPath": "key.shiftEnter",
    "promptToken": "sr.key.shiftEnter",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Shift+Enter",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.space": {
    "helperPath": "key.space",
    "promptToken": "sr.key.space",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Space",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.escape": {
    "helperPath": "key.escape",
    "promptToken": "sr.key.escape",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Escape",
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "key.mod.a": {
    "helperPath": "key.mod.a",
    "promptToken": "sr.key.mod.a",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Mod+A",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.mod.backspace": {
    "helperPath": "key.mod.backspace",
    "promptToken": "sr.key.mod.backspace",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Mod+Backspace",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.mod.delete": {
    "helperPath": "key.mod.delete",
    "promptToken": "sr.key.mod.delete",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Mod+Delete",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.mod.z": {
    "helperPath": "key.mod.z",
    "promptToken": "sr.key.mod.z",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Mod+Z",
    "defaultAllowedIn": [],
    "public": true
  },
  "key.mod.shiftZ": {
    "helperPath": "key.mod.shiftZ",
    "promptToken": "sr.key.mod.shiftZ",
    "kind": "invoke",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "fixedKey": "Mod+Shift+Z",
    "defaultAllowedIn": [],
    "public": true
  },
  "heading.next": {
    "helperPath": "heading.next",
    "promptToken": "sr.heading.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "keyboard.findNextHeading",
      "guidepup-nvda": "keyboard.moveToNextHeading",
      "guidepup-virtual": "commands.moveToNextHeading"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.previous": {
    "helperPath": "heading.previous",
    "promptToken": "sr.heading.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "keyboard.findPreviousHeading",
      "guidepup-nvda": "keyboard.moveToPreviousHeading",
      "guidepup-virtual": "commands.moveToPreviousHeading"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.1.next": {
    "helperPath": "heading.level1.next",
    "promptToken": "sr.heading.level.1.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel1",
      "guidepup-virtual": "commands.moveToNextHeadingLevel1"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.1.previous": {
    "helperPath": "heading.level1.previous",
    "promptToken": "sr.heading.level.1.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel1",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel1"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.2.next": {
    "helperPath": "heading.level2.next",
    "promptToken": "sr.heading.level.2.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel2",
      "guidepup-virtual": "commands.moveToNextHeadingLevel2"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.2.previous": {
    "helperPath": "heading.level2.previous",
    "promptToken": "sr.heading.level.2.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel2",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel2"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.3.next": {
    "helperPath": "heading.level3.next",
    "promptToken": "sr.heading.level.3.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel3",
      "guidepup-virtual": "commands.moveToNextHeadingLevel3"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.3.previous": {
    "helperPath": "heading.level3.previous",
    "promptToken": "sr.heading.level.3.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel3",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel3"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.4.next": {
    "helperPath": "heading.level4.next",
    "promptToken": "sr.heading.level.4.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel4",
      "guidepup-virtual": "commands.moveToNextHeadingLevel4"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.4.previous": {
    "helperPath": "heading.level4.previous",
    "promptToken": "sr.heading.level.4.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel4",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel4"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.5.next": {
    "helperPath": "heading.level5.next",
    "promptToken": "sr.heading.level.5.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel5",
      "guidepup-virtual": "commands.moveToNextHeadingLevel5"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.5.previous": {
    "helperPath": "heading.level5.previous",
    "promptToken": "sr.heading.level.5.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel5",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel5"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.6.next": {
    "helperPath": "heading.level6.next",
    "promptToken": "sr.heading.level.6.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextHeadingLevel6",
      "guidepup-virtual": "commands.moveToNextHeadingLevel6"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "heading.level.6.previous": {
    "helperPath": "heading.level6.previous",
    "promptToken": "sr.heading.level.6.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel6",
      "guidepup-virtual": "commands.moveToPreviousHeadingLevel6"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "form.next": {
    "helperPath": "form.next",
    "promptToken": "sr.form.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "keyboard.findNextControl",
      "guidepup-nvda": "keyboard.moveToNextFormField",
      "guidepup-virtual": "commands.moveToNextForm"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "form.previous": {
    "helperPath": "form.previous",
    "promptToken": "sr.form.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "keyboard.findPreviousControl",
      "guidepup-nvda": "keyboard.moveToPreviousFormField",
      "guidepup-virtual": "commands.moveToPreviousForm"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "link.next": {
    "helperPath": "link.next",
    "promptToken": "sr.link.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextLink",
      "guidepup-virtual": "commands.moveToNextLink"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "link.previous": {
    "helperPath": "link.previous",
    "promptToken": "sr.link.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousLink",
      "guidepup-virtual": "commands.moveToPreviousLink"
    },
    "defaultAllowedIn": [
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "button.next": {
    "helperPath": "button.next",
    "promptToken": "sr.button.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "commander.FIND_NEXT_BUTTON",
      "guidepup-nvda": "keyboard.moveToNextButton"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda"
    ],
    "public": true
  },
  "button.previous": {
    "helperPath": "button.previous",
    "promptToken": "sr.button.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "commander.FIND_PREVIOUS_BUTTON",
      "guidepup-nvda": "keyboard.moveToPreviousButton"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda"
    ],
    "public": true
  },
  "landmark.next": {
    "helperPath": "landmark.next",
    "promptToken": "sr.landmark.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "commander.FIND_NEXT_LANDMARK",
      "guidepup-nvda": "keyboard.moveToNextLandmark",
      "guidepup-virtual": "commands.moveToNextLandmark"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "landmark.previous": {
    "helperPath": "landmark.previous",
    "promptToken": "sr.landmark.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {
      "guidepup-voiceover": "commander.FIND_PREVIOUS_LANDMARK",
      "guidepup-nvda": "keyboard.moveToPreviousLandmark",
      "guidepup-virtual": "commands.moveToPreviousLandmark"
    },
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "list.next": {
    "helperPath": "list.next",
    "promptToken": "sr.list.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextList"
    },
    "defaultAllowedIn": [
      "guidepup-nvda"
    ],
    "public": true
  },
  "list.previous": {
    "helperPath": "list.previous",
    "promptToken": "sr.list.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousList"
    },
    "defaultAllowedIn": [
      "guidepup-nvda"
    ],
    "public": true
  },
  "table.next": {
    "helperPath": "table.next",
    "promptToken": "sr.table.next",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToNextTable"
    },
    "defaultAllowedIn": [
      "guidepup-nvda"
    ],
    "public": true
  },
  "table.previous": {
    "helperPath": "table.previous",
    "promptToken": "sr.table.previous",
    "kind": "catalog",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-nvda"
    ],
    "catalogIdsByBackend": {
      "guidepup-nvda": "keyboard.moveToPreviousTable"
    },
    "defaultAllowedIn": [
      "guidepup-nvda"
    ],
    "public": true
  },
  "read.itemText": {
    "helperPath": "read.itemText",
    "promptToken": "sr.read.itemText",
    "kind": "read",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "read.itemTextLog": {
    "helperPath": "read.itemTextLog",
    "promptToken": "sr.read.itemTextLog",
    "kind": "read",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "read.lastSpokenPhrase": {
    "helperPath": "read.lastSpokenPhrase",
    "promptToken": "sr.read.lastSpokenPhrase",
    "kind": "read",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "read.spokenPhraseLog": {
    "helperPath": "read.spokenPhraseLog",
    "promptToken": "sr.read.spokenPhraseLog",
    "kind": "read",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "clear.itemTextLog": {
    "helperPath": "clear.itemTextLog",
    "promptToken": "sr.clear.itemTextLog",
    "kind": "maintenance",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  },
  "clear.spokenPhraseLog": {
    "helperPath": "clear.spokenPhraseLog",
    "promptToken": "sr.clear.spokenPhraseLog",
    "kind": "maintenance",
    "argumentKind": "none",
    "backendSupport": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "catalogIdsByBackend": {},
    "defaultAllowedIn": [
      "guidepup-voiceover",
      "guidepup-nvda",
      "guidepup-virtual"
    ],
    "public": true
  }
} as const;
export const SCREEN_READER_HELPER_PATH_TO_SEMANTIC = {
  "next": "next",
  "previous": "previous",
  "act": "act",
  "interact": "interact",
  "stopInteracting": "stopInteracting",
  "type": "type",
  "click": "click",
  "key.tab": "key.tab",
  "key.shiftTab": "key.shiftTab",
  "key.home": "key.home",
  "key.end": "key.end",
  "key.arrow.up": "key.arrow.up",
  "key.arrow.down": "key.arrow.down",
  "key.arrow.left": "key.arrow.left",
  "key.arrow.right": "key.arrow.right",
  "key.backspace": "key.backspace",
  "key.delete": "key.delete",
  "key.enter": "key.enter",
  "key.shiftEnter": "key.shiftEnter",
  "key.space": "key.space",
  "key.escape": "key.escape",
  "key.mod.a": "key.mod.a",
  "key.mod.backspace": "key.mod.backspace",
  "key.mod.delete": "key.mod.delete",
  "key.mod.z": "key.mod.z",
  "key.mod.shiftZ": "key.mod.shiftZ",
  "heading.next": "heading.next",
  "heading.previous": "heading.previous",
  "heading.level1.next": "heading.level.1.next",
  "heading.level1.previous": "heading.level.1.previous",
  "heading.level2.next": "heading.level.2.next",
  "heading.level2.previous": "heading.level.2.previous",
  "heading.level3.next": "heading.level.3.next",
  "heading.level3.previous": "heading.level.3.previous",
  "heading.level4.next": "heading.level.4.next",
  "heading.level4.previous": "heading.level.4.previous",
  "heading.level5.next": "heading.level.5.next",
  "heading.level5.previous": "heading.level.5.previous",
  "heading.level6.next": "heading.level.6.next",
  "heading.level6.previous": "heading.level.6.previous",
  "form.next": "form.next",
  "form.previous": "form.previous",
  "link.next": "link.next",
  "link.previous": "link.previous",
  "button.next": "button.next",
  "button.previous": "button.previous",
  "landmark.next": "landmark.next",
  "landmark.previous": "landmark.previous",
  "list.next": "list.next",
  "list.previous": "list.previous",
  "table.next": "table.next",
  "table.previous": "table.previous",
  "read.itemText": "read.itemText",
  "read.itemTextLog": "read.itemTextLog",
  "read.lastSpokenPhrase": "read.lastSpokenPhrase",
  "read.spokenPhraseLog": "read.spokenPhraseLog",
  "clear.itemTextLog": "clear.itemTextLog",
  "clear.spokenPhraseLog": "clear.spokenPhraseLog"
} as const;
export const SCREEN_READER_SEMANTICS = [
  "next",
  "previous",
  "act",
  "interact",
  "stopInteracting",
  "press",
  "type",
  "click",
  "key.tab",
  "key.shiftTab",
  "key.home",
  "key.end",
  "key.arrow.up",
  "key.arrow.down",
  "key.arrow.left",
  "key.arrow.right",
  "key.backspace",
  "key.delete",
  "key.enter",
  "key.shiftEnter",
  "key.space",
  "key.escape",
  "key.mod.a",
  "key.mod.backspace",
  "key.mod.delete",
  "key.mod.z",
  "key.mod.shiftZ",
  "heading.next",
  "heading.previous",
  "heading.level.1.next",
  "heading.level.1.previous",
  "heading.level.2.next",
  "heading.level.2.previous",
  "heading.level.3.next",
  "heading.level.3.previous",
  "heading.level.4.next",
  "heading.level.4.previous",
  "heading.level.5.next",
  "heading.level.5.previous",
  "heading.level.6.next",
  "heading.level.6.previous",
  "form.next",
  "form.previous",
  "link.next",
  "link.previous",
  "button.next",
  "button.previous",
  "landmark.next",
  "landmark.previous",
  "list.next",
  "list.previous",
  "table.next",
  "table.previous",
  "read.itemText",
  "read.itemTextLog",
  "read.lastSpokenPhrase",
  "read.spokenPhraseLog",
  "clear.itemTextLog",
  "clear.spokenPhraseLog"
] as const;
export const SCREEN_READER_SEMANTIC_LABELS = "next, previous, act, interact, stopInteracting, press, type, click, key.tab, key.shiftTab, key.home, key.end, key.arrow.up, key.arrow.down, key.arrow.left, key.arrow.right, key.backspace, key.delete, key.enter, key.shiftEnter, key.space, key.escape, key.mod.a, key.mod.backspace, key.mod.delete, key.mod.z, key.mod.shiftZ, heading.next, heading.previous, heading.level.1.next, heading.level.1.previous, heading.level.2.next, heading.level.2.previous, heading.level.3.next, heading.level.3.previous, heading.level.4.next, heading.level.4.previous, heading.level.5.next, heading.level.5.previous, heading.level.6.next, heading.level.6.previous, form.next, form.previous, link.next, link.previous, button.next, button.previous, landmark.next, landmark.previous, list.next, list.previous, table.next, table.previous, read.itemText, read.itemTextLog, read.lastSpokenPhrase, read.spokenPhraseLog, clear.itemTextLog, clear.spokenPhraseLog" as const;
export const SCREEN_READER_PUBLIC_SEMANTICS = [
  "next",
  "previous",
  "act",
  "interact",
  "stopInteracting",
  "type",
  "click",
  "key.tab",
  "key.shiftTab",
  "key.home",
  "key.end",
  "key.arrow.up",
  "key.arrow.down",
  "key.arrow.left",
  "key.arrow.right",
  "key.backspace",
  "key.delete",
  "key.enter",
  "key.shiftEnter",
  "key.space",
  "key.escape",
  "key.mod.a",
  "key.mod.backspace",
  "key.mod.delete",
  "key.mod.z",
  "key.mod.shiftZ",
  "heading.next",
  "heading.previous",
  "heading.level.1.next",
  "heading.level.1.previous",
  "heading.level.2.next",
  "heading.level.2.previous",
  "heading.level.3.next",
  "heading.level.3.previous",
  "heading.level.4.next",
  "heading.level.4.previous",
  "heading.level.5.next",
  "heading.level.5.previous",
  "heading.level.6.next",
  "heading.level.6.previous",
  "form.next",
  "form.previous",
  "link.next",
  "link.previous",
  "button.next",
  "button.previous",
  "landmark.next",
  "landmark.previous",
  "list.next",
  "list.previous",
  "table.next",
  "table.previous",
  "read.itemText",
  "read.itemTextLog",
  "read.lastSpokenPhrase",
  "read.spokenPhraseLog",
  "clear.itemTextLog",
  "clear.spokenPhraseLog"
] as const;
export const SCREEN_READER_CLI_TOKENS = [
  "sr.next",
  "sr.previous",
  "sr.act",
  "sr.interact",
  "sr.stopInteracting",
  "sr.type",
  "sr.click",
  "sr.key.tab",
  "sr.key.shiftTab",
  "sr.key.home",
  "sr.key.end",
  "sr.key.arrow.up",
  "sr.key.arrow.down",
  "sr.key.arrow.left",
  "sr.key.arrow.right",
  "sr.key.backspace",
  "sr.key.delete",
  "sr.key.enter",
  "sr.key.shiftEnter",
  "sr.key.space",
  "sr.key.escape",
  "sr.key.mod.a",
  "sr.key.mod.backspace",
  "sr.key.mod.delete",
  "sr.key.mod.z",
  "sr.key.mod.shiftZ",
  "sr.heading.next",
  "sr.heading.previous",
  "sr.heading.level.1.next",
  "sr.heading.level.1.previous",
  "sr.heading.level.2.next",
  "sr.heading.level.2.previous",
  "sr.heading.level.3.next",
  "sr.heading.level.3.previous",
  "sr.heading.level.4.next",
  "sr.heading.level.4.previous",
  "sr.heading.level.5.next",
  "sr.heading.level.5.previous",
  "sr.heading.level.6.next",
  "sr.heading.level.6.previous",
  "sr.form.next",
  "sr.form.previous",
  "sr.link.next",
  "sr.link.previous",
  "sr.button.next",
  "sr.button.previous",
  "sr.landmark.next",
  "sr.landmark.previous",
  "sr.list.next",
  "sr.list.previous",
  "sr.table.next",
  "sr.table.previous",
  "sr.read.itemText",
  "sr.read.itemTextLog",
  "sr.read.lastSpokenPhrase",
  "sr.read.spokenPhraseLog",
  "sr.clear.itemTextLog",
  "sr.clear.spokenPhraseLog"
] as const;
export const SCREEN_READER_CLI_TOKEN_LABELS = "sr.next, sr.previous, sr.act, sr.interact, sr.stopInteracting, sr.type, sr.click, sr.key.tab, sr.key.shiftTab, sr.key.home, sr.key.end, sr.key.arrow.up, sr.key.arrow.down, sr.key.arrow.left, sr.key.arrow.right, sr.key.backspace, sr.key.delete, sr.key.enter, sr.key.shiftEnter, sr.key.space, sr.key.escape, sr.key.mod.a, sr.key.mod.backspace, sr.key.mod.delete, sr.key.mod.z, sr.key.mod.shiftZ, sr.heading.next, sr.heading.previous, sr.heading.level.1.next, sr.heading.level.1.previous, sr.heading.level.2.next, sr.heading.level.2.previous, sr.heading.level.3.next, sr.heading.level.3.previous, sr.heading.level.4.next, sr.heading.level.4.previous, sr.heading.level.5.next, sr.heading.level.5.previous, sr.heading.level.6.next, sr.heading.level.6.previous, sr.form.next, sr.form.previous, sr.link.next, sr.link.previous, sr.button.next, sr.button.previous, sr.landmark.next, sr.landmark.previous, sr.list.next, sr.list.previous, sr.table.next, sr.table.previous, sr.read.itemText, sr.read.itemTextLog, sr.read.lastSpokenPhrase, sr.read.spokenPhraseLog, sr.clear.itemTextLog, sr.clear.spokenPhraseLog" as const;
export const SCREEN_READER_PROMPT_TOKEN_TO_SEMANTIC = {
  "sr.next": "next",
  "sr.previous": "previous",
  "sr.act": "act",
  "sr.interact": "interact",
  "sr.stopInteracting": "stopInteracting",
  "sr.type": "type",
  "sr.click": "click",
  "sr.key.tab": "key.tab",
  "sr.key.shiftTab": "key.shiftTab",
  "sr.key.home": "key.home",
  "sr.key.end": "key.end",
  "sr.key.arrow.up": "key.arrow.up",
  "sr.key.arrow.down": "key.arrow.down",
  "sr.key.arrow.left": "key.arrow.left",
  "sr.key.arrow.right": "key.arrow.right",
  "sr.key.backspace": "key.backspace",
  "sr.key.delete": "key.delete",
  "sr.key.enter": "key.enter",
  "sr.key.shiftEnter": "key.shiftEnter",
  "sr.key.space": "key.space",
  "sr.key.escape": "key.escape",
  "sr.key.mod.a": "key.mod.a",
  "sr.key.mod.backspace": "key.mod.backspace",
  "sr.key.mod.delete": "key.mod.delete",
  "sr.key.mod.z": "key.mod.z",
  "sr.key.mod.shiftZ": "key.mod.shiftZ",
  "sr.heading.next": "heading.next",
  "sr.heading.previous": "heading.previous",
  "sr.heading.level.1.next": "heading.level.1.next",
  "sr.heading.level.1.previous": "heading.level.1.previous",
  "sr.heading.level.2.next": "heading.level.2.next",
  "sr.heading.level.2.previous": "heading.level.2.previous",
  "sr.heading.level.3.next": "heading.level.3.next",
  "sr.heading.level.3.previous": "heading.level.3.previous",
  "sr.heading.level.4.next": "heading.level.4.next",
  "sr.heading.level.4.previous": "heading.level.4.previous",
  "sr.heading.level.5.next": "heading.level.5.next",
  "sr.heading.level.5.previous": "heading.level.5.previous",
  "sr.heading.level.6.next": "heading.level.6.next",
  "sr.heading.level.6.previous": "heading.level.6.previous",
  "sr.form.next": "form.next",
  "sr.form.previous": "form.previous",
  "sr.link.next": "link.next",
  "sr.link.previous": "link.previous",
  "sr.button.next": "button.next",
  "sr.button.previous": "button.previous",
  "sr.landmark.next": "landmark.next",
  "sr.landmark.previous": "landmark.previous",
  "sr.list.next": "list.next",
  "sr.list.previous": "list.previous",
  "sr.table.next": "table.next",
  "sr.table.previous": "table.previous",
  "sr.read.itemText": "read.itemText",
  "sr.read.itemTextLog": "read.itemTextLog",
  "sr.read.lastSpokenPhrase": "read.lastSpokenPhrase",
  "sr.read.spokenPhraseLog": "read.spokenPhraseLog",
  "sr.clear.itemTextLog": "clear.itemTextLog",
  "sr.clear.spokenPhraseLog": "clear.spokenPhraseLog"
} as const;
export const SCREEN_READER_SEMANTICS_BY_BACKEND = {
  "guidepup-voiceover": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "press",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "form.next",
    "form.previous",
    "button.next",
    "button.previous",
    "landmark.next",
    "landmark.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ],
  "guidepup-nvda": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "press",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "heading.level.1.next",
    "heading.level.1.previous",
    "heading.level.2.next",
    "heading.level.2.previous",
    "heading.level.3.next",
    "heading.level.3.previous",
    "heading.level.4.next",
    "heading.level.4.previous",
    "heading.level.5.next",
    "heading.level.5.previous",
    "heading.level.6.next",
    "heading.level.6.previous",
    "form.next",
    "form.previous",
    "link.next",
    "link.previous",
    "button.next",
    "button.previous",
    "landmark.next",
    "landmark.previous",
    "list.next",
    "list.previous",
    "table.next",
    "table.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ],
  "guidepup-virtual": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "press",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "heading.level.1.next",
    "heading.level.1.previous",
    "heading.level.2.next",
    "heading.level.2.previous",
    "heading.level.3.next",
    "heading.level.3.previous",
    "heading.level.4.next",
    "heading.level.4.previous",
    "heading.level.5.next",
    "heading.level.5.previous",
    "heading.level.6.next",
    "heading.level.6.previous",
    "form.next",
    "form.previous",
    "link.next",
    "link.previous",
    "landmark.next",
    "landmark.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ]
} as const;
export const SCREEN_READER_PUBLIC_SEMANTICS_BY_BACKEND = {
  "guidepup-voiceover": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "form.next",
    "form.previous",
    "button.next",
    "button.previous",
    "landmark.next",
    "landmark.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ],
  "guidepup-nvda": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "heading.level.1.next",
    "heading.level.1.previous",
    "heading.level.2.next",
    "heading.level.2.previous",
    "heading.level.3.next",
    "heading.level.3.previous",
    "heading.level.4.next",
    "heading.level.4.previous",
    "heading.level.5.next",
    "heading.level.5.previous",
    "heading.level.6.next",
    "heading.level.6.previous",
    "form.next",
    "form.previous",
    "link.next",
    "link.previous",
    "button.next",
    "button.previous",
    "landmark.next",
    "landmark.previous",
    "list.next",
    "list.previous",
    "table.next",
    "table.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ],
  "guidepup-virtual": [
    "next",
    "previous",
    "act",
    "interact",
    "stopInteracting",
    "type",
    "click",
    "key.tab",
    "key.shiftTab",
    "key.home",
    "key.end",
    "key.arrow.up",
    "key.arrow.down",
    "key.arrow.left",
    "key.arrow.right",
    "key.backspace",
    "key.delete",
    "key.enter",
    "key.shiftEnter",
    "key.space",
    "key.escape",
    "key.mod.a",
    "key.mod.backspace",
    "key.mod.delete",
    "key.mod.z",
    "key.mod.shiftZ",
    "heading.next",
    "heading.previous",
    "heading.level.1.next",
    "heading.level.1.previous",
    "heading.level.2.next",
    "heading.level.2.previous",
    "heading.level.3.next",
    "heading.level.3.previous",
    "heading.level.4.next",
    "heading.level.4.previous",
    "heading.level.5.next",
    "heading.level.5.previous",
    "heading.level.6.next",
    "heading.level.6.previous",
    "form.next",
    "form.previous",
    "link.next",
    "link.previous",
    "landmark.next",
    "landmark.previous",
    "read.itemText",
    "read.itemTextLog",
    "read.lastSpokenPhrase",
    "read.spokenPhraseLog",
    "clear.itemTextLog",
    "clear.spokenPhraseLog"
  ]
} as const;
export const SCREEN_READER_INVOKE_SEMANTICS = [
  "next",
  "previous",
  "act",
  "interact",
  "stopInteracting",
  "press",
  "type",
  "click",
  "key.tab",
  "key.shiftTab",
  "key.home",
  "key.end",
  "key.arrow.up",
  "key.arrow.down",
  "key.arrow.left",
  "key.arrow.right",
  "key.backspace",
  "key.delete",
  "key.enter",
  "key.shiftEnter",
  "key.space",
  "key.escape",
  "key.mod.a",
  "key.mod.backspace",
  "key.mod.delete",
  "key.mod.z",
  "key.mod.shiftZ"
] as const;
export const SCREEN_READER_READ_SEMANTICS = [
  "read.itemText",
  "read.itemTextLog",
  "read.lastSpokenPhrase",
  "read.spokenPhraseLog"
] as const;
export const SCREEN_READER_MAINTENANCE_SEMANTICS = [
  "clear.itemTextLog",
  "clear.spokenPhraseLog"
] as const;
export const SCREEN_READER_CATALOG_SEMANTICS = [
  "heading.next",
  "heading.previous",
  "heading.level.1.next",
  "heading.level.1.previous",
  "heading.level.2.next",
  "heading.level.2.previous",
  "heading.level.3.next",
  "heading.level.3.previous",
  "heading.level.4.next",
  "heading.level.4.previous",
  "heading.level.5.next",
  "heading.level.5.previous",
  "heading.level.6.next",
  "heading.level.6.previous",
  "form.next",
  "form.previous",
  "link.next",
  "link.previous",
  "button.next",
  "button.previous",
  "landmark.next",
  "landmark.previous",
  "list.next",
  "list.previous",
  "table.next",
  "table.previous"
] as const;
export const SCREEN_READER_CATALOG_IDS_BY_SEMANTIC = {
  "heading.next": {
    "guidepup-voiceover": "keyboard.findNextHeading",
    "guidepup-nvda": "keyboard.moveToNextHeading",
    "guidepup-virtual": "commands.moveToNextHeading"
  },
  "heading.previous": {
    "guidepup-voiceover": "keyboard.findPreviousHeading",
    "guidepup-nvda": "keyboard.moveToPreviousHeading",
    "guidepup-virtual": "commands.moveToPreviousHeading"
  },
  "heading.level.1.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel1",
    "guidepup-virtual": "commands.moveToNextHeadingLevel1"
  },
  "heading.level.1.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel1",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel1"
  },
  "heading.level.2.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel2",
    "guidepup-virtual": "commands.moveToNextHeadingLevel2"
  },
  "heading.level.2.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel2",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel2"
  },
  "heading.level.3.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel3",
    "guidepup-virtual": "commands.moveToNextHeadingLevel3"
  },
  "heading.level.3.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel3",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel3"
  },
  "heading.level.4.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel4",
    "guidepup-virtual": "commands.moveToNextHeadingLevel4"
  },
  "heading.level.4.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel4",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel4"
  },
  "heading.level.5.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel5",
    "guidepup-virtual": "commands.moveToNextHeadingLevel5"
  },
  "heading.level.5.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel5",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel5"
  },
  "heading.level.6.next": {
    "guidepup-nvda": "keyboard.moveToNextHeadingLevel6",
    "guidepup-virtual": "commands.moveToNextHeadingLevel6"
  },
  "heading.level.6.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousHeadingLevel6",
    "guidepup-virtual": "commands.moveToPreviousHeadingLevel6"
  },
  "form.next": {
    "guidepup-voiceover": "keyboard.findNextControl",
    "guidepup-nvda": "keyboard.moveToNextFormField",
    "guidepup-virtual": "commands.moveToNextForm"
  },
  "form.previous": {
    "guidepup-voiceover": "keyboard.findPreviousControl",
    "guidepup-nvda": "keyboard.moveToPreviousFormField",
    "guidepup-virtual": "commands.moveToPreviousForm"
  },
  "link.next": {
    "guidepup-nvda": "keyboard.moveToNextLink",
    "guidepup-virtual": "commands.moveToNextLink"
  },
  "link.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousLink",
    "guidepup-virtual": "commands.moveToPreviousLink"
  },
  "button.next": {
    "guidepup-voiceover": "commander.FIND_NEXT_BUTTON",
    "guidepup-nvda": "keyboard.moveToNextButton"
  },
  "button.previous": {
    "guidepup-voiceover": "commander.FIND_PREVIOUS_BUTTON",
    "guidepup-nvda": "keyboard.moveToPreviousButton"
  },
  "landmark.next": {
    "guidepup-voiceover": "commander.FIND_NEXT_LANDMARK",
    "guidepup-nvda": "keyboard.moveToNextLandmark",
    "guidepup-virtual": "commands.moveToNextLandmark"
  },
  "landmark.previous": {
    "guidepup-voiceover": "commander.FIND_PREVIOUS_LANDMARK",
    "guidepup-nvda": "keyboard.moveToPreviousLandmark",
    "guidepup-virtual": "commands.moveToPreviousLandmark"
  },
  "list.next": {
    "guidepup-nvda": "keyboard.moveToNextList"
  },
  "list.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousList"
  },
  "table.next": {
    "guidepup-nvda": "keyboard.moveToNextTable"
  },
  "table.previous": {
    "guidepup-nvda": "keyboard.moveToPreviousTable"
  }
} as const;
export const SCREEN_READER_SEMANTIC_BY_CATALOG_ID = {
  "keyboard.findNextHeading": "heading.next",
  "keyboard.moveToNextHeading": "heading.next",
  "commands.moveToNextHeading": "heading.next",
  "keyboard.findPreviousHeading": "heading.previous",
  "keyboard.moveToPreviousHeading": "heading.previous",
  "commands.moveToPreviousHeading": "heading.previous",
  "keyboard.moveToNextHeadingLevel1": "heading.level.1.next",
  "commands.moveToNextHeadingLevel1": "heading.level.1.next",
  "keyboard.moveToPreviousHeadingLevel1": "heading.level.1.previous",
  "commands.moveToPreviousHeadingLevel1": "heading.level.1.previous",
  "keyboard.moveToNextHeadingLevel2": "heading.level.2.next",
  "commands.moveToNextHeadingLevel2": "heading.level.2.next",
  "keyboard.moveToPreviousHeadingLevel2": "heading.level.2.previous",
  "commands.moveToPreviousHeadingLevel2": "heading.level.2.previous",
  "keyboard.moveToNextHeadingLevel3": "heading.level.3.next",
  "commands.moveToNextHeadingLevel3": "heading.level.3.next",
  "keyboard.moveToPreviousHeadingLevel3": "heading.level.3.previous",
  "commands.moveToPreviousHeadingLevel3": "heading.level.3.previous",
  "keyboard.moveToNextHeadingLevel4": "heading.level.4.next",
  "commands.moveToNextHeadingLevel4": "heading.level.4.next",
  "keyboard.moveToPreviousHeadingLevel4": "heading.level.4.previous",
  "commands.moveToPreviousHeadingLevel4": "heading.level.4.previous",
  "keyboard.moveToNextHeadingLevel5": "heading.level.5.next",
  "commands.moveToNextHeadingLevel5": "heading.level.5.next",
  "keyboard.moveToPreviousHeadingLevel5": "heading.level.5.previous",
  "commands.moveToPreviousHeadingLevel5": "heading.level.5.previous",
  "keyboard.moveToNextHeadingLevel6": "heading.level.6.next",
  "commands.moveToNextHeadingLevel6": "heading.level.6.next",
  "keyboard.moveToPreviousHeadingLevel6": "heading.level.6.previous",
  "commands.moveToPreviousHeadingLevel6": "heading.level.6.previous",
  "keyboard.findNextControl": "form.next",
  "keyboard.moveToNextFormField": "form.next",
  "commands.moveToNextForm": "form.next",
  "keyboard.findPreviousControl": "form.previous",
  "keyboard.moveToPreviousFormField": "form.previous",
  "commands.moveToPreviousForm": "form.previous",
  "keyboard.moveToNextLink": "link.next",
  "commands.moveToNextLink": "link.next",
  "keyboard.moveToPreviousLink": "link.previous",
  "commands.moveToPreviousLink": "link.previous",
  "commander.FIND_NEXT_BUTTON": "button.next",
  "keyboard.moveToNextButton": "button.next",
  "commander.FIND_PREVIOUS_BUTTON": "button.previous",
  "keyboard.moveToPreviousButton": "button.previous",
  "commander.FIND_NEXT_LANDMARK": "landmark.next",
  "keyboard.moveToNextLandmark": "landmark.next",
  "commands.moveToNextLandmark": "landmark.next",
  "commander.FIND_PREVIOUS_LANDMARK": "landmark.previous",
  "keyboard.moveToPreviousLandmark": "landmark.previous",
  "commands.moveToPreviousLandmark": "landmark.previous",
  "keyboard.moveToNextList": "list.next",
  "keyboard.moveToPreviousList": "list.previous",
  "keyboard.moveToNextTable": "table.next",
  "keyboard.moveToPreviousTable": "table.previous"
} as const;
