import {afterEach,describe,expect,it} from 'vitest';
import {createServer,type Server} from 'node:http';
import {createTestBrowserSession} from './helpers/browser.js';
const closers:(()=>Promise<unknown>)[]=[];afterEach(async()=>{for(const f of closers.splice(0).reverse())await f()});
async function server(){const requests:string[]=[];const s=createServer((req,res)=>{requests.push(`${req.method} ${req.url}`);res.setHeader('content-type','text/html');res.end('<!doctype html><a href="/edit">Edit</a><a href="/search?q=test">Search</a><form method="post" action="/submit"><button>Post</button></form>')});await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));closers.push(()=>new Promise<void>(r=>s.close(()=>r())));return{requests,url:`http://127.0.0.1:${(s.address() as {port:number}).port}`}}
describe('public-site read-only request boundary',()=>{
 it('blocks POST before transmission while allowing harmless GET search',async()=>{const site=await server();const session=await createTestBrowserSession(site.url,{navigation:{strategy:'same-origin',readOnly:true,denyUrlIncludes:['/edit']}});closers.push(()=>session.close());await session.page.locator('button').click();await new Promise(r=>setTimeout(r,80));expect(site.requests.some(r=>r.startsWith('POST'))).toBe(false);expect(session.takeBlockedNavigations().some(r=>r.reason.includes('Read-only'))).toBe(true);await session.page.locator('a').nth(1).click();expect(session.page.url()).toContain('/search?q=test')});
 it('blocks excluded URL and History paths without a request or URL mutation',async()=>{const site=await server();const session=await createTestBrowserSession(site.url,{navigation:{strategy:'allow-url-list',allowUrlList:[site.url],readOnly:true,denyUrlIncludes:['/edit','action=edit']}});closers.push(()=>session.close());await session.page.locator('a').first().click();await session.page.evaluate(()=>history.pushState(null,'','/?action=edit'));expect(session.page.url()).not.toContain('edit');expect(site.requests.some(r=>r.includes('/edit')||r.includes('action=edit'))).toBe(false)});
});

it('stops an HTTP access restriction before any model inference',async()=>{
 const s=createServer((_req,res)=>{res.writeHead(403,{'content-type':'text/html'});res.end('<title>Access denied</title><script>fetch("/challenge",{method:"POST"}).catch(()=>{})</script>Denied')});await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));closers.push(()=>new Promise<void>(r=>s.close(()=>r())));
 const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const out=await mkdtemp(join(tmpdir(),'rawstep-blocked-'));closers.push(()=>rm(out,{recursive:true,force:true}));const {runScreenshotTask}=await import('rawstep/screenshot');let calls=0;
 const trace=await runScreenshotTask({url:`http://127.0.0.1:${(s.address() as {port:number}).port}`,goal:'Read public page',navigation:{strategy:'same-origin',readOnly:true},verify:{all:[{titleIncludes:'Complete'}]}},{outDir:out,browserSessionFactory:createTestBrowserSession,policy:{decide:()=>{calls++;return {stop:'stuck'}}}});expect(calls).toBe(0);expect(trace.outcome).toMatchObject({status:'inconclusive',reason:'access-blocked',error:expect.stringContaining('HTTP 403')});expect(trace.events.find(e=>e.type==='browser.access-blocked')?.data).toMatchObject({status:403});
});
