import { describe,expect,it,vi } from 'vitest';
import { diagnoseScreenshotStop } from 'rawstep/screenshot';
import type { RunTrace } from '@rawstep/core/trace';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nV8AAAAASUVORK5CYII=';
const trace=()=>({runId:'r',task:{id:'t',goal:'Inspect'},outcome:{status:'failure',reason:'policy-stuck',policyStopSource:'exploration-guard'},events:[{id:'image',type:'keyboard.observation',source:'runner',redacted:false,data:{screenshot:{pngBase64:png,viewport:{w:1,h:1}}}},{id:'stop',type:'policy.decision',source:'policy',data:{step:2,decision:{stop:'stuck',stopSource:'exploration-guard'}}},{id:'hidden',type:'verifier.evidence',source:'verifier',data:{SECRET_DOM:'not allowed'}}]}) as unknown as RunTrace;
describe('bounded model stop hypotheses',()=>{
 it('scores only reason choices from screenshot and stripped history without mutating the result',async()=>{const original=trace(),before=JSON.stringify(original);const model={choose:vi.fn(async req=>({choiceId:'reason:other-unknown',model:{id:'fixture',runtime:'test'},probabilities:req.choices.map(()=>1/7)}))};const result=await diagnoseScreenshotStop(original,{model});expect(result).toMatchObject({status:'completed',hypothesis:'other-unknown',stopSource:'exploration-guard',screenshotEventId:'image'});expect(JSON.stringify(original)).toBe(before);expect(model.choose.mock.calls[0]![0]).toMatchObject({purpose:'stop-reason'});expect(JSON.stringify(model.choose.mock.calls)).not.toMatch(/SECRET_DOM|verifier/)});
 it('timeout is separate from original task failure and produces no action',async()=>{const original=trace();const result=await diagnoseScreenshotStop(original,{timeoutMs:10,model:{choose:async()=>new Promise(()=>{})}});expect(result.status).toBe('failed');expect(original.outcome?.reason).toBe('policy-stuck')});
 it('does not send an old screenshot when the final screenshot was redacted',async()=>{const original=trace();original.events.push({...original.events[0]!,id:'private',redacted:true,data:{screenshot:'[REDACTED]'}});const choose=vi.fn();expect((await diagnoseScreenshotStop(original,{model:{choose}})).status).toBe('unavailable');expect(choose).not.toHaveBeenCalled()});
 it('does not classify successful runs and keeps model errors private',async()=>{const original=trace();original.events[1]!.data={decision:{stop:'success'}};expect((await diagnoseScreenshotStop(original,{model:{choose:vi.fn()}})).status).toBe('not-applicable');const result=await diagnoseScreenshotStop(trace(),{model:{choose:async()=>{throw Error('PRIVATE')}}});expect(JSON.stringify(result)).not.toContain('PRIVATE')});
});
