import { describe, expect, it, vi } from 'vitest';
import { FOCUS_CONTEXT_CHOICES, restrictChoicesByVisualFocus, ScreenshotDecisionPolicy, screenshotChoices, type ScreenshotModelRequest } from 'rawstep/screenshot';
import type { DecisionPolicy } from '@rawstep/core/contracts';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nV8AAAAASUVORK5CYII=';
const input=():Parameters<DecisionPolicy['decide']>[0]=>({goal:'Use query field',observation:{kind:'keyboard',screenshot:{pngBase64:png,viewport:{w:1,h:1}},window:{id:'w',startedAt:'2026-01-01',endedAt:'2026-01-01',reason:'test'}},history:[],allowedActions:{keys:['Tab','Enter','Space','Backspace','Delete'],intents:[],inputKeys:['query'],replaceText:true},inputs:{query:{sensitive:true}},signal:new AbortController().signal});
const response=(choiceId:string,probabilities?:number[])=>({choiceId,probabilities,model:{id:'test-double',runtime:'unit'}});
const choices=()=>screenshotChoices(input().allowedActions);
describe('opt-in screenshot-only focus gate',()=>{
 it.each(['focus:none','focus:uncertain','focus:other'])('blocks text/activation for %s',choiceId=>{const scores=FOCUS_CONTEXT_CHOICES.map(c=>c.id===choiceId?1:0);expect(restrictChoicesByVisualFocus(choices(),response(choiceId,scores)).map(c=>c.id)).toEqual(['key:Tab','stop:success']);const giveUp=screenshotChoices(input().allowedActions,{modelGiveUp:true});expect(restrictChoicesByVisualFocus(giveUp,response(choiceId,scores)).map(c=>c.id)).toEqual(['key:Tab','stop:success','stop:uncertain','stop:stuck'])});
 it('fails closed for absent scores and low/contradictory confidence',()=>{for(const scores of [undefined,[.6,.1,.1,.1,.1],[.2,.8,0,0,0]])expect(restrictChoicesByVisualFocus(choices(),response('focus:editable-target',scores)).some(c=>c.id.startsWith('type:'))).toBe(false)});
 it('separates an editable target from an activation target',()=>{const edit=restrictChoicesByVisualFocus(choices(),response('focus:editable-target',[.9,.025,.025,.025,.025]));expect(edit.some(c=>c.id==='type:query')).toBe(true);expect(edit.some(c=>c.id==='key:Enter')).toBe(true);expect(edit.some(c=>c.id==='key:Space')).toBe(false);const button=restrictChoicesByVisualFocus(choices(),response('focus:activation-target',[.025,.9,.025,.025,.025]));expect(button.some(c=>c.id==='key:Space')).toBe(true);expect(button.some(c=>c.id==='replace:query')).toBe(false)});
 it.each([-1,NaN,Infinity,1.1])('rejects invalid threshold %s',v=>{expect(()=>new ScreenshotDecisionPolicy({model:{choose:async()=>response('key:Tab')},focusGate:{minimumProbability:v}})).toThrow(/threshold/)});
 it('builds two fresh allowlisted requests without private values, DOM/AX or verifier leakage',async()=>{const requests:ScreenshotModelRequest[]=[];const p=new ScreenshotDecisionPolicy({focusGate:{},historyLimit:1,model:{choose:async r=>{requests.push(structuredClone(r));return r.purpose==='focus-context'?response('focus:none',[0,0,0,1,0]):response('key:Tab')}}});const value=input();Object.assign(value.observation,{dom:'HIDDEN_DOM',verifier:'HIDDEN_VERIFY',ax:'HIDDEN_AX'});expect(await p.decide(value)).toEqual({action:{kind:'key',key:'Tab'}});expect(requests).toHaveLength(2);expect(requests[0]!.purpose).toBe('focus-context');expect(requests[1]!.choices.some(c=>c.id==='key:Enter')).toBe(false);expect(JSON.stringify(requests)).not.toMatch(/PRIVATE_|HIDDEN_/);expect(p.takeDecisionEvidence()).toEqual([expect.objectContaining({kind:'visual-focus-gate',choiceId:'focus:none'}),expect.objectContaining({kind:'model-inference',choiceId:'key:Tab'})])});
 it('never permits a blocked choice even if the action adapter returns one',async()=>{const p=new ScreenshotDecisionPolicy({focusGate:{},model:{choose:async r=>r.purpose==='focus-context'?response('focus:uncertain'):response('key:Enter')}});await expect(p.decide(input())).rejects.toThrow(/unknown choice/)});
 it('honors cancellation after the focus comparison before an action call',async()=>{const controller=new AbortController();const choose=vi.fn(async()=>{controller.abort('stop');return response('focus:none')});const p=new ScreenshotDecisionPolicy({focusGate:{},model:{choose}});await expect(p.decide({...input(),signal:controller.signal})).rejects.toBe('stop');expect(choose).toHaveBeenCalledTimes(1);expect(p.takeDecisionEvidence()).toEqual([])});
 it('keeps the original single-call path when opt-in is absent',async()=>{const choose=vi.fn(async()=>response('key:Enter'));const p=new ScreenshotDecisionPolicy({model:{choose}});expect(await p.decide(input())).toEqual({action:{kind:'key',key:'Enter'}});expect(choose).toHaveBeenCalledTimes(1)});
});
