import {describe,it,expect,afterEach} from 'vitest';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createTestBrowserSession} from './helpers/browser.js';import {collectBrowserDiagnostics} from '@rawstep/browser/profiles';
const cleanups:(()=>Promise<void>)[]=[];afterEach(async()=>{for(const f of cleanups.splice(0).reverse())await f()});
async function open(scenario:string,defect:string){const u=pathToFileURL(resolve('fixtures/visual-study/controls.html'));u.search=new URLSearchParams({scenario,defect}).toString();const s=await createTestBrowserSession(u.href);cleanups.push(()=>s.close());return s.page}
describe('paired synthetic controls: independent observed conditions, not model or WCAG accuracy',()=>{
 it.each(['normal','invisible'])('records focus indicator style for search %s',async defect=>{const p=await open('search',defect);await p.keyboard.press('Tab');const d=await collectBrowserDiagnostics(p);expect(d.policyVisible).toBe(false);expect(d.focus.id).toBe('#query');expect(d.findings.some(f=>f.code==='focus-indicator-not-detected')).toBe(defect==='invisible')});
 it.each(['normal','trap'])('records actual repeated focus for settings %s',async defect=>{const p=await open('settings',defect);await p.keyboard.press('Tab');const before=await p.evaluate(()=>document.activeElement?.id);await p.keyboard.press('Tab');const after=await p.evaluate(()=>document.activeElement?.id);expect(before===after).toBe(defect==='trap');expect(after).toBe(defect==='trap'?'preview':'apply')});
 it.each(['normal','occluded'])('records sampled focus occlusion for settings %s',async defect=>{const p=await open('settings',defect);await p.keyboard.press('Tab');await p.keyboard.press('Tab');const d=await collectBrowserDiagnostics(p);expect(d.focus.id).toBe('#apply');expect(d.findings.some(f=>f.code==='focus-center-occluded')).toBe(defect==='occluded')});
 it('normal keyboard actions independently complete the settings goal',async()=>{const p=await open('settings','normal');await p.keyboard.press('Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');expect(await p.locator('#result').innerText()).toBe('Settings applied')});
});

it('rejects a gated model false success with the independent verifier and no dispatched action',async()=>{
 const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const {runScreenshotTask,ScreenshotDecisionPolicy}=await import('rawstep/screenshot');
 const out=await mkdtemp(join(tmpdir(),'rawstep-gated-false-success-'));cleanups.push(()=>rm(out,{recursive:true,force:true}));const u=pathToFileURL(resolve('fixtures/visual-study/controls.html'));u.search='scenario=search&defect=normal';let calls=0;
 const trace=await runScreenshotTask({mode:'keyboard',url:u.href,goal:'Enter the query',maxSteps:3,verify:{all:[{textVisibleExact:'Results for query'}]}},{outDir:out,browserSessionFactory:createTestBrowserSession,policy:new ScreenshotDecisionPolicy({focusGate:{},model:{choose:async request=>{calls++;return {choiceId:request.purpose==='focus-context'?'focus:none':'stop:success',...(request.purpose==='focus-context'?{probabilities:[0,0,0,1,0]}:{}),model:{id:'fixture-only',runtime:'test'}}}}})});
 expect(trace.events.find(e=>e.type==='policy.decision')?.data).toMatchObject({decision:{stop:'success'}});expect(calls).toBe(2);expect(trace.outcome).toMatchObject({status:'failure',reason:'verification-failed'});expect(trace.events.filter(e=>e.type==='action.result')).toHaveLength(0);
});
