export { describeInputs, matchesText, MAX_SCRIPT_SOURCE, resolveTask, validateNavigation } from './contracts/index.js';
export type { ActivatedAnnouncementVerificationRule, AllowedActions, AnyVerificationRule, Backend, BackendAction, BackendCapabilities, BackendKeyboardObservation, BackendObservation, BackendOperationOptions, BackendOutput, BackendRunContext, BackendSession, BackendSpeechObservation, Decision, DecisionPolicy, DomEventVerificationRule, EventVerificationRule, FocusedVerificationRule, HistoryEntry, InputDescriptor, KeyboardObservation, NavigationPolicy, NotVerificationRule, Observation, ObservedEventKind, PolicyAction, RequestVerificationRule, ResolvedNavigationPolicy, ResponseVerificationRule, ScreenReaderObservation, ScreenshotObservation, ScriptCheckError, ScriptVerificationRule, Task, TaskInputOptions, TextMatcher, VerificationRecord, VerificationRuleRecord, VerificationWitness, VerifyRule, VerifyRuleType, VerifySpec } from './contracts/index.js';
export { createRedactor, FileTraceSink, hydrateScreenshots, isScreenshotRef, MemoryTraceSink, readTrace, REDACTED, screenshotSha256, TRACE_SCHEMA_VERSION, traceFilePath, TraceRecorder, validateTrace, writeJsonAtomic } from './trace/index.js';
export type { AppendEventOptions, CollectionWindow, RunOutcome, RunTrace, ScreenshotRef, TraceEnvironment, TraceEvent, TraceEventType, TraceRecorderOptions, TraceSink, TraceSource, TraceTaskMetadata } from './trace/index.js';
export type { AppliedProfile, BrowserDiagnostic, DiagnosticFinding, EnvironmentProfile, ProfileSetting } from './profiles/types.js';
export { BUILTIN_PROFILES, DEFAULT_PROFILE, resolveEnvironmentProfile } from './profiles/schema.js';
export { SCREENSHOT_KEYS } from './screenshot.js';
export { isLoopbackHostname, isLoopbackUrl, LOOPBACK_HOSTNAMES, RAWSTEP_DEFAULTS } from './defaults.js';
export { findRawstepError, RawstepError } from './errors.js';
export type { RawstepErrorCode, RawstepOutcomeHint } from './errors.js';
