import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import type {
  ScreenReaderCapabilities,
  ScreenReaderPerformCommand
} from "@rawstep/action-catalog";
import {
  BACKEND_SPEC,
  type ScreenReaderBackendId
} from "../../definition/src/backends/source";

const VIRTUAL_INDEX_ARG_HINT = 'args: {"index": number}';
const requireFromHere = createRequire(__filename);
const scriptDir = __dirname;
const definitionGeneratedPath = resolve(
  scriptDir,
  "../../definition/src/backends/generated-capabilities.ts"
);
const guidepupPackageRoot = dirname(requireFromHere.resolve("@guidepup/guidepup/package.json"));

type CommandRecord = Record<string, {
  description?: string;
  representation?: string;
}>;

type CommanderCommandRecord = Record<string, string>;

type VirtualModuleShape = {
  virtual: {
    commands: Record<string, unknown>;
    next?: unknown;
    previous?: unknown;
    act?: unknown;
    perform?: unknown;
    press?: unknown;
    type?: unknown;
    interact?: unknown;
    stopInteracting?: unknown;
    click?: unknown;
    itemText?: unknown;
    itemTextLog?: unknown;
    lastSpokenPhrase?: unknown;
    spokenPhraseLog?: unknown;
    clearItemTextLog?: unknown;
    clearSpokenPhraseLog?: unknown;
  };
};

const voiceOverKeyCodeCommands = requireFromHere(
  join(guidepupPackageRoot, "lib/macOS/VoiceOver/keyCodeCommands.js")
).keyCodeCommands as CommandRecord;

const nvdaKeyCodeCommands = requireFromHere(
  join(guidepupPackageRoot, "lib/windows/NVDA/keyCodeCommands.js")
).keyCodeCommands as CommandRecord;

const voiceOverCommanderCommands = requireFromHere(
  join(guidepupPackageRoot, "lib/macOS/VoiceOver/CommanderCommands.js")
).CommanderCommands as CommanderCommandRecord;

const { virtual } = requireFromHere("@guidepup/virtual-screen-reader") as VirtualModuleShape;

async function main(): Promise<void> {
  const capabilitiesByBackend: Record<ScreenReaderBackendId, ScreenReaderCapabilities> = {
    "guidepup-voiceover": {
      invoke: {
        next: true,
        previous: true,
        act: true,
        interact: true,
        stopInteracting: true,
        press: true,
        type: true,
        click: true,
        perform: true,
        supportsRawPerform: BACKEND_SPEC["guidepup-voiceover"].supportsRawPerform
      },
      read: {
        itemText: true,
        itemTextLog: true,
        lastSpokenPhrase: true,
        spokenPhraseLog: true
      },
      maintenance: {
        clearItemTextLog: true,
        clearSpokenPhraseLog: true
      },
      performCatalog: [
        ...createKeyboardPerformCommands(voiceOverKeyCodeCommands),
        ...createCommanderPerformCommands(voiceOverCommanderCommands)
      ]
    },
    "guidepup-nvda": {
      invoke: {
        next: true,
        previous: true,
        act: true,
        interact: true,
        stopInteracting: true,
        press: true,
        type: true,
        click: true,
        perform: true,
        supportsRawPerform: BACKEND_SPEC["guidepup-nvda"].supportsRawPerform
      },
      read: {
        itemText: true,
        itemTextLog: true,
        lastSpokenPhrase: true,
        spokenPhraseLog: true
      },
      maintenance: {
        clearItemTextLog: true,
        clearSpokenPhraseLog: true
      },
      performCatalog: createKeyboardPerformCommands(nvdaKeyCodeCommands)
    },
    "guidepup-virtual": {
      invoke: {
        next: typeof virtual.next === "function",
        previous: typeof virtual.previous === "function",
        act: typeof virtual.act === "function",
        interact: typeof virtual.interact === "function",
        stopInteracting: typeof virtual.stopInteracting === "function",
        press: typeof virtual.press === "function",
        type: typeof virtual.type === "function",
        click: typeof virtual.click === "function",
        perform: typeof virtual.perform === "function",
        supportsRawPerform: BACKEND_SPEC["guidepup-virtual"].supportsRawPerform
      },
      read: {
        itemText: typeof virtual.itemText === "function",
        itemTextLog: typeof virtual.itemTextLog === "function",
        lastSpokenPhrase: typeof virtual.lastSpokenPhrase === "function",
        spokenPhraseLog: typeof virtual.spokenPhraseLog === "function"
      },
      maintenance: {
        clearItemTextLog: typeof virtual.clearItemTextLog === "function",
        clearSpokenPhraseLog: typeof virtual.clearSpokenPhraseLog === "function"
      },
      performCatalog: createVirtualPerformCommands(virtual.commands)
    }
  };

  const moduleSource = [
    "// This file is generated by packages/runtime/scripts/generate-backend-capabilities.ts.",
    "// Do not edit by hand.",
    "",
    'import type { ScreenReaderBackendId, ScreenReaderCapabilities } from "@rawstep/action-catalog";',
    "",
    `export const SCREEN_READER_BACKEND_CAPABILITIES = ${JSON.stringify(capabilitiesByBackend, null, 2)} as const satisfies Record<`,
    "  ScreenReaderBackendId,",
    "  ScreenReaderCapabilities",
    ">;",
    ""
  ].join("\n");

  await writeFile(definitionGeneratedPath, moduleSource, "utf8");
}

function createKeyboardPerformCommands(commandMap: CommandRecord): ScreenReaderPerformCommand[] {
  return Object.entries(commandMap).map(([propertyName, metadata]) => ({
    id: `keyboard.${propertyName}`,
    label: metadata.representation?.trim() || propertyName,
    description: metadata.description?.trim() || humanizePropertyName(propertyName)
  }));
}

function createCommanderPerformCommands(commandMap: CommanderCommandRecord): ScreenReaderPerformCommand[] {
  return Object.entries(commandMap).map(([enumKey, value]) => ({
    id: `commander.${enumKey}`,
    label: value,
    description: humanizeEnumKey(enumKey)
  }));
}

function createVirtualPerformCommands(commands: Record<string, unknown>): ScreenReaderPerformCommand[] {
  return Object.keys(commands).map((propertyName) => ({
    id: `commands.${propertyName}`,
    label: propertyName,
    description: humanizePropertyName(propertyName),
    ...(getVirtualArgsHint(propertyName) ? { argsHint: getVirtualArgsHint(propertyName) } : {})
  }));
}

function humanizePropertyName(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replaceAll(/[_-]+/g, " ")
    .trim();
}

function humanizeEnumKey(value: string): string {
  return value
    .toLowerCase()
    .replaceAll("_", " ")
    .trim();
}

function getVirtualArgsHint(propertyName: string): string | undefined {
  return new Set([
    "jumpToControlledElement",
    "jumpToErrorMessageElement",
    "moveToNextAlternateReadingOrderElement",
    "moveToPreviousAlternateReadingOrderElement"
  ]).has(propertyName)
    ? VIRTUAL_INDEX_ARG_HINT
    : undefined;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
