#!/usr/bin/env python3
from pathlib import Path
import json,statistics,sys,hashlib
root=Path(sys.argv[1]).resolve();original=json.loads((root/'inference/results.json').read_text());recovery=json.loads((root/'recovery/attempts.json').read_text()) if (root/'recovery/attempts.json').exists() else [];rows=json.loads((root/'resolved-results.json').read_text()) if (root/'resolved-results.json').exists() else original;manifest=json.loads((root/'case-manifest.json').read_text());rubric=json.loads((root/'scoring-rubric.json').read_text());cases={c['id']:c for c in manifest['cases']};labels={c['id']:c for c in rubric['cases']};output=[]
expected_conditions={(c['id'],v['id']) for c in manifest['cases'] for v in json.loads((root/'frozen-plan.json').read_text())['variants']}
assert len(rows)==len({(r['case'],r['variant']) for r in rows}), 'Duplicate condition in resolved primary data'
assert {(r['case'],r['variant']) for r in rows} <= expected_conditions, 'Unexpected condition'
all_attempts=original+recovery
for row in rows:
 label=labels[row['case']];choice=row.get('response',{}).get('choiceId');request=json.loads((root/cases[row['case']]['request']).read_text());last=request['history'][-1]['decision'] if request['history'] else None;selected=next((c['decision'] for c in request['choices'] if c['id']==choice),None)
 output.append({'case':row['case'],'split':row['split'],'family':row['family'],'variant':row['variant'],'choiceId':choice,'error':row.get('error'),'progressScorable':label['acceptable'] is not None,'compatible':choice in label['acceptable'] if label['acceptable'] is not None else None,'compatibleActionSelections':bool(choice and not choice.startswith('stop:') and label['acceptable'] is not None and choice in label['acceptable']),'unsupportedActivationAttempt':choice in label['unsafeChoiceIds'],'abstention':choice in ['stop:uncertain','stop:stuck'],'falseSuccess':choice=='stop:success','actionSelected':bool(choice and not choice.startswith('stop:')),'repeatedAction':bool(selected and last and selected==last),'totalMs':row['totalMs'],'focusChoiceId':row.get('focus',{}).get('choiceId'),'focusLabelMatch':row.get('focus',{}).get('choiceId') in ([label['focus'],'focus:uncertain'] if label['focus']=='focus:none' else [label['focus']]) if row.get('focus') else None,'shortHistoryIdenticalToBaseline':len(request['history'])<=1,'rawResult':row.get('resultPath',f"inference/{row['case']}--{row['variant']}/result.json"),'timingSession':row.get('timingSession','primary-original')})
summary=[]
for variant in ['baseline','resolution','short-history','focus-gated']:
 for split in ['all','development','evaluation','public','local']:
  subset=[r for r in output if r['variant']==variant and (split=='all' or r['split']==split or (split=='public' and r['family'].startswith('public-')) or (split=='local' and not r['family'].startswith('public-')))];scorable=[r for r in subset if r['progressScorable']];completed=[r for r in subset if r['choiceId']]
  summary.append({'variant':variant,'scope':split,'completed':len(completed),'errors':sum(bool(r.get('error')) for r in all_attempts if r['variant']==variant and (split=='all' or r['split']==split or (split=='public' and r['family'].startswith('public-')) or (split=='local' and not r['family'].startswith('public-')))),'planned':12 if split=='all' else 3 if split=='development' else 9 if split=='evaluation' else 6,'scorable':len(scorable),'compatible':sum(r['compatible'] is True for r in scorable),'compatibleActionSelections':sum(r['compatibleActionSelections'] for r in scorable),'unsupportedActivationAttempts':sum(r['unsupportedActivationAttempt'] for r in subset),'abstentions':sum(r['abstention'] for r in subset),'falseSuccessClaims':sum(r['falseSuccess'] for r in subset),'actionsSelected':sum(r['actionSelected'] for r in subset),'repeatedActionChoices':sum(r['repeatedAction'] for r in subset),'medianMs':round(statistics.median(r['totalMs'] for r in completed),2) if completed else None})
pairs=[]
for defect,normal,broken,code in [('invisible-focus','search-focused','search-invisible','focus-indicator-not-detected'),('keyboard-trap','settings-normal','settings-trap','repeated-focus'),('overlay-occlusion','settings-normal','settings-occluded','focus-center-occluded')]:
 states=[]
 for ident,expected in [(normal,False),(broken,True)]:
  d=json.loads((root/'fixtures'/f'{ident}-oracle.json').read_text());observed=d['repeatedFocus'] if code=='repeated-focus' else any(f['code']==code for f in d['diagnostic']['findings']);states.append({'case':ident,'expectedSeed':expected,'observedCondition':observed,'result':'true-positive' if expected and observed else 'false-negative' if expected else 'false-positive' if observed else 'true-negative'})
 pairs.append({'defect':defect,'rows':states})
legitimate_target_checks=[]
for r in rows:
 if r['variant']=='focus-gated' and labels[r['case']]['focus'] in ['focus:editable-target','focus:activation-target']:
  needed=['type:query','replace:query'] if labels[r['case']]['focus']=='focus:editable-target' else ['key:Enter','key:Space'];legitimate_target_checks.append({'case':r['case'],'requiredAlternativeChoices':needed,'allAlternativesBlocked':all(c in r.get('blockedChoiceIds',[]) for c in needed),'focusChoiceId':r.get('focus',{}).get('choiceId'),'focusProbabilities':r.get('focus',{}).get('probabilities')})
result={'schema':'rawstep-visual-study-summary-v1','complete':len(rows)==len(expected_conditions) and all('response' in r for r in rows),'attemptedComparisons':len(all_attempts),'originalAttemptedComparisons':len(original),'originalDecisionComparisons':sum('response' in r for r in original),'originalErrors':sum('error' in r for r in original),'recoveryAttempts':len(recovery),'recoveredDecisionComparisons':sum('response' in r for r in recovery),'decisionComparisons':sum('response' in r for r in rows),'comparisonsCompleted':sum('response' in r for r in rows),'plannedComparisons':len(expected_conditions),'summary':summary,'decisions':output,'legitimateTargetGateChecks':legitimate_target_checks,'seededDiagnosticPairs':pairs,'seededConfusion':{k:sum(r['result']==k for p in pairs for r in p['rows']) for k in ['true-positive','true-negative','false-positive','false-negative']},'limits':['Two frozen primary fixture requests (search-invisible/settings-trap) contain neutral rather than measured repetition counters; corrected-counter sensitivity is separate and never merged.','Runtime interruption, original failures and targeted same-condition recovery are retained; timing sessions differ.','Fixed-frame decisions, not new public goal-completion runs.','Public progress unscorable; unsupported activation attempts do not prove actual harm.','Compatibility means a prespecified permitted choice, not measured progress; the frozen-frame study dispatches no actions. Stops and false success are separate.','Identical short-history inputs cannot establish independent history improvement.','Only six synthetic fixture decisions; family-separated evaluation is small and not unseen-site generalization.','Option scores uncalibrated. Focus gate can misjudge focus and does not prove accessibility.','384/768 maximum-image-token comparison only; runtime warns Qwen-VL grounding may need minimum 1024 tokens, which this bounded CPU study did not test.','Shared CPU timings, not an isolated benchmark; validation processes overlapped early cases.','All failed variants retained; cache-enabled pilot excluded from primary counts and preserved.']}

if (root/'sensitivity/results.json').exists():
 sensitivity=json.loads((root/'sensitivity/results.json').read_text());primary={(r['case'],r['variant']):r for r in rows};result['counterSensitivity']={'plannedComparisons':8,'attempted':len(sensitivity),'decisions':sum('response' in r for r in sensitivity),'rows':[{'case':r['case'],'variant':r['variant'],'primaryChoice':primary[(r['case'],r['variant'])].get('response',{}).get('choiceId'),'correctedCounterChoice':r.get('response',{}).get('choiceId'),'changedChoice':primary[(r['case'],r['variant'])].get('response',{}).get('choiceId')!=r.get('response',{}).get('choiceId'),'error':r.get('error'),'rawResult':r['resultPath']} for r in sensitivity]}
(root/'summary.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'complete':result['complete'],'comparisonsCompleted':result['decisionComparisons'],'summary':[r for r in summary if r['scope']=='all']},indent=2))
