import { useEffect, useState } from 'react';
import { Square, RotateCcw, ExternalLink } from 'lucide-react';
import type { Experiment, RunRecord, RetryPreview } from '../../shared/config';
import { api } from '../api';
import { Field, Choice, SectionHeader } from '../components/forms';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Checkbox } from '../components/ui/checkbox';
import { Table, TableCaption, TableHeader, TableRow, TableHead, TableBody, TableCell } from '../components/ui/table';
import type { PageProps } from './types';
const postLabels: Record<string, string> = { pending: '대기', complete: '완료', failed: '실패', skipped: '생략' };
const labels: Record<string, string> = { queued: '대기', running: '실행 중', success: '성공', failure: '실패', inconclusive: '판단 불가', cancelled: '취소', interrupted: '중단' };
export function HistoryPage({ experiments, focus, ...props }: PageProps & { experiments: Experiment[]; focus?: string }) {
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('all');
  const [selection, setSelection] = useState<string[]>([]);
  const [detail, setDetail] = useState<string>(focus ?? '');
  const [retry, setRetry] = useState<{ experiment: string; run: RunRecord; preview: RetryPreview }>();
  const all = experiments.flatMap(e => e.runs.map(run => ({ run, experiment: e })));
  const selected = all.find(r => r.run.id === detail);
  const rows = all.filter(({ run }) => (!query || (run.snapshot.taskName + run.snapshot.model.name + run.snapshot.prompt.name).toLowerCase().includes(query.toLowerCase())) && (filter === 'all' || run.state === filter));
  const compare = all.filter(r => selection.includes(r.run.id));
  return <>
    <SectionHeader title="실행 이력" description="독립 검증 결과와 모델 판단, 분석 상태를 나누어 확인합니다." />
    <div className="mb-6 grid max-w-xl gap-4 sm:grid-cols-2"><Field label="작업·모델·프롬프트 검색" value={query} onChange={setQuery} /><Choice label="상태 필터" value={filter} onChange={setFilter} options={[{ id: 'all', name: '전체 상태' }, ...Object.entries(labels).map(([id, name]) => ({ id, name }))]} /></div>
    <Card><CardContent className="pt-4">{rows.length ? <Table><TableCaption>각 실행은 독립된 브라우저와 고정된 설정을 사용합니다.</TableCaption><TableHeader><TableRow><TableHead>비교</TableHead><TableHead>작업</TableHead><TableHead>모델·프롬프트</TableHead><TableHead>결과</TableHead><TableHead>분석·보고서</TableHead><TableHead>동작</TableHead></TableRow></TableHeader><TableBody>{rows.map(({ run, experiment }) => <TableRow key={run.id}><TableCell><Checkbox aria-label={'비교 ' + run.id} checked={selection.includes(run.id)} onCheckedChange={v => setSelection(v ? [...selection, run.id] : selection.filter(id => id !== run.id))} /></TableCell><TableCell><Button variant="link" className="h-auto p-0" onClick={() => setDetail(run.id)}>{run.snapshot.taskName}</Button><p className="mt-1 text-xs text-muted-foreground">{run.snapshot.mode} · 반복 {run.repeat}</p></TableCell><TableCell>{run.snapshot.model.name}<p className="text-xs text-muted-foreground">{run.snapshot.prompt.name} · v{run.snapshot.prompt.version}</p></TableCell><TableCell><Badge variant={run.state === 'success' ? 'secondary' : 'outline'}>{labels[run.state]}</Badge><p className="mt-1 text-xs text-muted-foreground">{run.outcome?.reason ?? run.error}</p></TableCell><TableCell className="text-xs">{postLabels[run.analysisStatus]} / {postLabels[run.reportStatus]}</TableCell><TableCell><div className="flex gap-1">{['queued', 'running'].includes(run.state) ? <><Button size="sm" variant="ghost" disabled={props.busy} onClick={() => void props.act(() => api('/experiments/' + experiment.id + '/runs/' + run.id + '/cancel', { method: 'POST' }))}>실행 취소</Button><Button size="sm" variant="outline" disabled={props.busy} onClick={() => void props.act(() => api('/experiments/' + experiment.id + '/cancel', { method: 'POST' }))}><Square aria-hidden="true" />큐 중지</Button></> : <Button size="sm" variant="ghost" disabled={props.busy || !run.taskFile} title={!run.taskFile ? '이 초기 기록에는 원본 Task 파일 경로가 없습니다. 실험 화면에서 새 실행을 구성하세요.' : undefined} onClick={() => void props.act(async () => { const preview = await api<RetryPreview>('/experiments/' + experiment.id + '/runs/' + run.id + '/retry'); setRetry({ experiment: experiment.id, run, preview }); })}><RotateCcw aria-hidden="true" />새 실행</Button>}</div></TableCell></TableRow>)}</TableBody></Table> : <div className="py-16 text-center text-sm text-muted-foreground">표시할 실행이 없습니다. 실험 화면에서 실행을 시작하세요.</div>}</CardContent></Card>
    {retry && <Card className="mt-6"><CardHeader><CardTitle>기존 조건으로 새 실행</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm">모델·프롬프트·허용 행동·환경은 기존 실행의 설정을 사용합니다. 입력값은 현재 작업 파일에서 다시 읽습니다.</p><p className="text-sm text-muted-foreground">{retry.preview.changedFields.length ? '현재 작업 파일과 다른 항목: ' + retry.preview.changedFields.join(', ') : '입력값 외 작업 조건에 변경이 없습니다.'}</p>{retry.preview.changedFields.length > 0 && <details><summary className="cursor-pointer text-sm">작업 조건 차이 확인</summary><pre className="max-h-80 overflow-auto bg-muted p-3 text-xs">{JSON.stringify({ 기존: retry.preview.original, 현재: retry.preview.current }, null, 2)}</pre></details>}<div className="flex gap-2"><Button disabled={props.busy} onClick={() => void props.act(async () => { const e = await api<Experiment>('/experiments/' + retry.experiment + '/runs/' + retry.run.id + '/retry', { method: 'POST', body: { revision: retry.preview.revision } }); setDetail(e.runs[0]!.id); setRetry(undefined); })}>기존 조건으로 실행</Button><Button variant="outline" onClick={() => setRetry(undefined)}>닫기</Button></div></CardContent></Card>}
    {compare.length > 0 && <Card className="mt-6"><CardHeader><CardTitle>선택한 실행 비교 {compare.length}개</CardTitle></CardHeader><CardContent><Table><TableCaption>실제로 적용한 조건과 기록된 결과 비교</TableCaption><TableHeader><TableRow><TableHead>모델·프롬프트</TableHead><TableHead>모드·환경</TableHead><TableHead>허용 기능</TableHead><TableHead>결과·단계</TableHead><TableHead>시간</TableHead></TableRow></TableHeader><TableBody>{compare.map(({ run }) => <TableRow key={run.id}><TableCell>{run.snapshot.model.name}<p className="text-xs text-muted-foreground">{run.snapshot.prompt.name} v{run.snapshot.prompt.version}</p></TableCell><TableCell>{run.snapshot.mode}<p className="text-xs text-muted-foreground">{run.environmentId}</p></TableCell><TableCell className="max-w-64 break-words text-xs">{[...run.permissions.keys, ...run.permissions.intents].join(', ')} · 입력 {run.permissions.typeText ? '허용' : '금지'} · 교체 {run.permissions.replaceText ? '허용' : '금지'}</TableCell><TableCell>{labels[run.state]} · {run.outcome?.steps ?? '—'}</TableCell><TableCell>{run.startedAt && run.endedAt ? ((Date.parse(run.endedAt) - Date.parse(run.startedAt)) / 1000).toFixed(1) + 's' : '—'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
    {selected && <RunDetail key={selected.run.id} run={selected.run} experiment={selected.experiment.id} />}
  </>;
}
function RunDetail({ run, experiment }: { run: RunRecord; experiment: string }) {
  const [events, setEvents] = useState<{ id: string; seq: number; type: string; timestamp: string; data: unknown; redacted: boolean }[]>([]), [error, setError] = useState('');
  const prefix = '/experiments/' + experiment + '/runs/' + run.id;
  useEffect(() => {
    let disposed = false;
    const refresh = () => void api<typeof events>(prefix + '/events').then(e => { if (!disposed) { setEvents(e); setError(''); } }).catch(e => { if (!disposed) setError((e as Error).message); });
    refresh(); const timer = run.endedAt ? undefined : setInterval(refresh, 1500); return () => { disposed = true; clearInterval(timer); };
  }, [prefix, run.endedAt]);
  return <Card className="mt-6"><CardHeader><CardTitle>실행 상세 — {run.snapshot.taskName}</CardTitle><p className="text-xs text-muted-foreground">{run.id} · {labels[run.state]}</p><div className="flex flex-wrap gap-2">{run.reportStatus === 'complete' && <Button variant="outline" size="sm" asChild><a href={'/api' + prefix + '/report'} target="_blank" rel="noreferrer">보고서<ExternalLink aria-hidden="true" /></a></Button>}{run.outcome && <Button variant="outline" size="sm" asChild><a href={'/api' + prefix + '/trace'}>Trace 내려받기</a></Button>}{run.analysisStatus === 'complete' && <Button variant="outline" size="sm" asChild><a href={'/api' + prefix + '/analysis'}>분석 내려받기</a></Button>}{run.diagnoseStop && run.outcome && <Button variant="outline" size="sm" asChild><a href={'/api' + prefix + '/stop-reason'}>중단 진단 내려받기</a></Button>}</div></CardHeader><CardContent className="grid gap-5">
    {run.snapshot.mode === 'screenreader' && run.snapshot.globals.backend === 'simulation' && <p className="text-sm text-muted-foreground">모의 VoiceOver 실행입니다. 실제 네이티브 발화 검증 결과가 아닙니다.</p>}
    {run.promptSource === 'server' && <p className="text-sm text-muted-foreground">이 /choose 서버는 지침을 소유합니다. UI의 기본 지침은 실제 적용 문구를 의미하지 않으며, 프롬프트 편집 실행은 제한됩니다.</p>}
    {run.outcome && <p className="text-sm">기록된 실행 결과: {labels[run.outcome.status] ?? run.outcome.status} · {run.outcome.reason ?? '—'}</p>}
    {run.error && <p role="alert" className="text-sm text-destructive">{run.error}</p>}{run.analysisError && <p role="alert" className="text-sm text-destructive">{run.analysisError}</p>}{error && <p role="alert">{error}</p>}
    <details><summary className="cursor-pointer text-sm font-medium">적용한 설정과 프롬프트</summary><pre className="mt-3 max-h-96 overflow-auto rounded-md bg-muted p-4 text-xs">{JSON.stringify({ ...run.snapshot, promptSource: run.promptSource ?? 'client', analysisInstructions: run.analysisInstructions, permissions: run.permissions, permissionSource: run.permissionSource }, null, 2)}</pre></details>
    <h3 className="text-sm font-medium">단계별 기록 {events.length}개</h3><div className="grid max-h-[650px] gap-3 overflow-auto">{events.map(event => <details key={event.id} className="rounded-md border p-3"><summary className="cursor-pointer text-xs">{event.seq} · {event.type} · {event.redacted ? '가림 처리' : new Date(event.timestamp).toLocaleTimeString()}</summary>{event.type === 'keyboard.observation' && !event.redacted && <img className="my-3 w-full rounded-md" loading="lazy" src={'/api' + prefix + '/png/' + encodeURIComponent(event.id)} alt={'키보드 관찰 단계 ' + event.seq} />}<pre className="mt-3 overflow-auto text-xs">{JSON.stringify(event.data, null, 2)}</pre></details>)}</div>
  </CardContent></Card>;
}
