import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Field, Choice, SectionHeader } from '../components/forms';
import { api } from '../api';
import { EnvironmentFields } from '../components/EnvironmentFields';
import { PermissionsEditor } from '../components/PermissionsEditor';
import { Button } from '../components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/card';
import { Switch } from '../components/ui/switch';
import { Label } from '../components/ui/label';
import { defaultConfig, type DashboardConfig } from '../../shared/config';
import type { PageProps } from './types';

export function SettingsPage(props: PageProps) {
  const { t } = useTranslation();
  const [config, setConfig] = useState<DashboardConfig>(() => structuredClone(props.view.config));
  const [revision, setRevision] = useState(props.view.revision);
  const [environments, setEnvironments] = useState(JSON.stringify(config.environments, null, 2));
  const [capabilities, setCapabilities] = useState(props.view.capabilities);
  const [backendStatus, setBackendStatus] = useState('');
  const globals = config.globals;
  const update = (part: Partial<typeof globals>) => setConfig({ ...config, globals: { ...globals, ...part } });
  return <>
    <SectionHeader title={t('settingsPage.title')} description={t('settingsPage.description')}><Button variant="outline" onClick={() => { const defaults = defaultConfig(); setConfig({ ...config, globals: defaults.globals }); setEnvironments(JSON.stringify(defaults.environments, null, 2)); setBackendStatus(''); void props.act(async () => setCapabilities(await api<typeof capabilities>('/capabilities', { method: 'POST', body: { globals: defaults.globals } }))); }}>{t('settingsPage.editDefaults')}</Button><Button disabled={props.busy} onClick={() => void props.act(async () => { const saved = await props.save({ ...config, environments: JSON.parse(environments) }, undefined, revision); setRevision(saved.revision); })}>{t('settingsPage.save')}</Button></SectionHeader>
    <div className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>{t('settingsPage.keyboardPermissions')}</CardTitle></CardHeader><CardContent><PermissionsEditor value={globals.keyboard} onChange={keyboard => update({ keyboard })} capabilities={capabilities.keyboard} /></CardContent></Card>
      <Card><CardHeader><CardTitle>{t('settingsPage.screenreaderPermissions')}</CardTitle></CardHeader><CardContent><PermissionsEditor value={globals.screenreader} onChange={screenreader => update({ screenreader })} capabilities={capabilities.screenreader} /></CardContent></Card>
      <Card><CardHeader><CardTitle>{t('settingsPage.runtimeTitle')}</CardTitle></CardHeader><CardContent className="grid gap-4"><Choice label={t('settingsPage.backendLabel')} value={globals.backend} onChange={backend => { const next = { ...globals, backend: backend as typeof globals.backend }; update({ backend: next.backend }); setBackendStatus(''); void props.act(async () => setCapabilities(await api<typeof capabilities>('/capabilities', { method: 'POST', body: { globals: next } }))); }} options={[{ id: 'simulation', name: t('settingsPage.backendSimulation') }, { id: 'voiceover', name: t('settingsPage.backendVoiceover') }, { id: 'nvda', name: t('settingsPage.backendNvda') }]} /><Field label={t('settingsPage.atEndpoint')} value={globals.atEndpoint} onChange={atEndpoint => update({ atEndpoint })} /><Field label={t('settingsPage.browserPath')} value={globals.browserExecutablePath} onChange={browserExecutablePath => update({ browserExecutablePath })} hint={t('settingsPage.browserPathHint')} /><div className="flex items-center gap-3"><Switch id="headless" checked={globals.headless} onCheckedChange={headless => update({ headless })} /><Label htmlFor="headless">{t('settingsPage.headless')}</Label></div><Button variant="outline" disabled={props.busy} onClick={() => void props.act(async () => { const result = await api<{ message: string }>('/backend/check', { method: 'POST', body: { globals } }); setBackendStatus(result.message); })}>{t('settingsPage.checkBackend')}</Button>{backendStatus && <p role="status" className="text-sm text-primary">{backendStatus}</p>}<p className="text-xs leading-5 text-muted-foreground">{t('settingsPage.nativeNote')}</p></CardContent></Card>
      <Card><CardHeader><CardTitle>{t('settingsPage.policyTitle')}</CardTitle></CardHeader><CardContent className="grid gap-4">{([['historyLimit', t('settingsPage.historyLimit')], ['maxStateVisits', t('settingsPage.maxStateVisits')], ['maxUnchangedTransitions', t('settingsPage.maxUnchangedTransitions')]] as const).map(([key, label]) => <Field key={key} label={label} type="number" value={String(globals.policy[key])} onChange={s => update({ policy: { ...globals.policy, [key]: Number(s) } })} />)}<div className="flex items-center gap-3"><Switch id="focus-gate" checked={globals.policy.focusGate} onCheckedChange={focusGate => update({ policy: { ...globals.policy, focusGate } })} /><Label htmlFor="focus-gate">{t('settingsPage.focusGate')}</Label></div><Choice label={t('settingsPage.repetitionGuard')} value={globals.policy.repetitionGuard} onChange={repetitionGuard => update({ policy: { ...globals.policy, repetitionGuard: repetitionGuard as typeof globals.policy.repetitionGuard } })} options={[{ id: 'auto', name: t('settingsPage.repetitionAuto') }, { id: 'on', name: t('settingsPage.repetitionOn') }, { id: 'off', name: t('settingsPage.repetitionOff') }]} /><div className="flex items-center gap-3"><Switch id="model-give-up" checked={globals.policy.modelGiveUp} onCheckedChange={modelGiveUp => update({ policy: { ...globals.policy, modelGiveUp } })} /><Label htmlFor="model-give-up">{t('settingsPage.modelGiveUp')}</Label></div><p className="text-xs leading-5 text-muted-foreground">{t('settingsPage.policyNote')}</p></CardContent></Card>
      <Card className="lg:col-span-2"><CardHeader><CardTitle>{t('settingsPage.analysisTitle')}</CardTitle></CardHeader><CardContent><Field label={t('settingsPage.analysisLabel')} multiline value={globals.analysisInstructions} onChange={analysisInstructions => update({ analysisInstructions })} hint={t('settingsPage.analysisHint')} /></CardContent></Card>
      <Card className="lg:col-span-2"><CardHeader><CardTitle>{t('settingsPage.environmentsTitle')}</CardTitle></CardHeader><CardContent className="grid gap-4"><EnvironmentFields json={environments} onChange={setEnvironments} profiles={props.view.profiles} /><details><summary className="cursor-pointer text-sm">{t('settingsPage.advancedEnvironments')}</summary><div className="mt-4"><Field label={t('settingsPage.environmentsJson')} value={environments} multiline onChange={setEnvironments} hint={t('settingsPage.environmentsJsonHint')} /></div></details><p className="text-xs text-muted-foreground">{t('settingsPage.defaultProfiles', { profiles: Object.keys(props.view.profiles).join(', ') })}</p></CardContent></Card>
    </div>
  </>;
}
